export const parkings = [
  {
    price: 86000,
    type: "parking",
    number: 11,
    styles: {
      clipPath: ``,
      width: "5%",
      height: "13.5%",
      left: "13%",
      top: "4%",
    },
  },
  {
    price: 86000,
    type: "parking",
    number: 10,
    styles: {
      clipPath: ``,
      width: "5%",
      height: "13.5%",
      left: "17.7%",
      top: "4%",
    },
  },
  {
    price: 86000,
    type: "parking",
    number: 19,
    styles: {
      clipPath: ``,
      width: "5%",
      height: "15%",
      left: "35.7%",
      top: "36.6%",
    },
  },
  {
    price: 86000,
    type: "parking",
    number: 18,
    styles: {
      clipPath: ``,
      width: "5%",
      height: "15%",
      left: "40.8%",
      top: "36.6%",
    },
  },
  {
    price: 86000,
    type: "parking",
    number: 14,
    styles: {
      clipPath: ``,
      width: "5%",
      height: "15%",
      left: "65.3%",
      top: "36.6%",
    },
  },
  {
    price: 86000,
    type: "parking",
    number: 32,
    styles: {
      clipPath: ``,
      width: "5%",
      height: "14%",
      top: "85.9%",
      left: "70.8%",
    },
  },
];

export const larders = [
  {
    id: 1,
    price: 86000,
    type: "larder",
    space: 12,
    rooms: 1,
    entrance: 5,
    status: "available",
    number: 11,
    styles: {
      clipPath: ``,
      width: "22.1%",
      height: "32.5%",
      top: "10%",
      left: "1.5%",
    },
  },
  {
    id: 2,
    price: 106000,
    type: "larder",
    space: 23,
    rooms: 2,
    entrance: 5,
    status: "available",
    number: 10,
    styles: {
      clipPath: ``,
      width: "16%",
      height: "33.5%",
      left: "60%",
      top: "54%",
    },
  },
];

export const flats = [
  {
    id: 1,
    name: "Студия",
    type: "flat",
    status: "available",
    number: 1,
    entrance: 5,
    rooms: 1,
    price: 4500000,
    finishingPrice: 477000,
    meterPrice: 75000,
    styles: { width: "16%", height: "34%", left: "24%", top: "9%" },
    layouts: ["image21.png", "image22.png"],
    space: 21.4,
    degree: 120,
    openDate: "2021-10-03T15:00:00.000+05:00",
    about: {
      title: "Отделка",
      text: [
        `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
        `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
      ],
      images: ["image28.jpg", "image29.jpg", "image28.jpg"],
    },
    options: [
      { title: "Кладовку", image: "image31.jpg" },
      { title: "Парковку", image: "image30.jpg" },
    ],
    flatNumber: 12,
    project: "Васнецово",
    projectId: 4,
    projectType: "ЖК",
    favored: false,
    finishingIn: false,
    level: 1,
    street: "10 лет Октября",
    district: "Пчкаловский",
    discount: "50%",
    newShapes: true,
    house: "2",
    kitchenSpace: 5.7,
    amount: 2,
  },
  {
    id: 2,
    name: "1-комн.",
    type: "flat",
    status: "booked",
    number: 2,
    entrance: 5,
    rooms: 1,
    price: 4000000,
    finishingPrice: 477000,
    meterPrice: 75000,
    layouts: ["image22.png", "image22.png"],
    space: 16.4,
    degree: 140,
    openDate: "2021-10-03T15:00:00.000+05:00",
    about: {
      title: "Отделка",
      text: [
        `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
        `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
      ],
      images: ["image29.jpg", "image28.jpg", "image29.jpg"],
    },
    options: [
      { title: "Кладовку", image: "image31.jpg" },
      { title: "Парковку", image: "image30.jpg" },
    ],
    flatNumber: 12,
    project: "Васнецово",
    projectId: 4,
    projectType: "ЖК",
    favored: false,
    finishingIn: false,
    level: 1,
    street: "10 лет Октября",
    district: "Пчкаловский",
    discount: "50%",
    newShapes: true,
    house: "2",
    kitchenSpace: 5.7,
    amount: 2,
  },
  {
    id: 3,
    name: "2-комн.",
    type: "flat",
    status: "sold",
    number: 3,
    entrance: 5,
    rooms: 2,
    price: 3600000,
    finishingPrice: 507000,
    meterPrice: 75000,
    layouts: ["image23.png", "image22.png"],
    house: "2",
    space: 21.4,
    degree: 0,
    openDate: "2021-10-03T15:00:00.000+05:00",
    about: {
      title: "Отделка",
      text: [
        `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
        `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
      ],
      images: ["image28.jpg", "image29.jpg", "image28.jpg"],
    },
    options: [
      { title: "Кладовку", image: "image31.jpg" },
      { title: "Парковку", image: "image30.jpg" },
    ],
    flatNumber: 12,
    project: "Васнецово",
    projectId: 4,
    projectType: "ЖК",
    favored: true,
    finishingIn: false,
    level: 1,
    street: "10 лет Октября",
    district: "Пчкаловский",
    discount: "50%",
    newShapes: true,
    kitchenSpace: 5.7,
    amount: 2,
  },
  {
    id: 4,
    name: "3-комн.",
    type: "flat",
    status: "available",
    number: 4,
    entrance: 5,
    rooms: 3,
    price: 4500000,
    finishingPrice: 577000,
    meterPrice: 75000,
    layouts: ["image23.png", "image22.png"],
    space: 40.4,
    degree: 70,
    openDate: "2021-10-03T15:00:00.000+05:00",
    about: {
      title: "Отделка",
      text: [
        `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
        `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
      ],
      images: ["image29.jpg", "image28.jpg", "image29.jpg"],
    },
    options: [
      { title: "Кладовку", image: "image31.jpg" },
      { title: "Парковку", image: "image30.jpg" },
    ],
    flatNumber: 12,
    project: "Васнецово",
    projectId: 4,
    projectType: "ЖК",
    favored: false,
    finishingIn: false,
    level: 1,
    street: "10 лет Октября",
    district: "Пчкаловский",
    discount: "50%",
    newShapes: true,
    house: "2",
    kitchenSpace: 5.7,
    amount: 2,
  },
  {
    id: 5,
    name: "4-комн.",
    type: "flat",
    status: "available",
    number: 5,
    entrance: 5,
    rooms: 4,
    price: 5500000,
    finishingPrice: 577000,
    meterPrice: 75000,
    layouts: ["image23.png", "image22.png"],
    space: 36.4,
    degree: 40,
    openDate: "2021-10-03T15:00:00.000+05:00",
    about: {
      title: "Отделка",
      text: [
        `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
        `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
      ],
      images: ["image28.jpg", "image29.jpg", "image28.jpg"],
    },
    options: [
      { title: "Кладовку", image: "image31.jpg" },
      { title: "Парковку", image: "image30.jpg" },
    ],
    flatNumber: 12,
    project: "Васнецово",
    projectId: 4,
    projectType: "ЖК",
    favored: false,
    finishingIn: false,
    level: 1,
    street: "10 лет Октября",
    district: "Пчкаловский",
    discount: "50%",
    newShapes: true,
    house: "2",
    kitchenSpace: 5.7,
    amount: 2,
  },
  {
    id: 6,
    name: "Студия",
    type: "flat",
    status: "available",
    number: 1,
    entrance: 5,
    rooms: 1,
    price: 4500000,
    finishingPrice: 477000,
    meterPrice: 75000,
    styles: { width: "16%", height: "34%", left: "24%", top: "9%" },
    layouts: ["image21.png", "image22.png"],
    space: 21.4,
    degree: 120,
    openDate: "2021-10-03T15:00:00.000+05:00",
    about: {
      title: "Отделка",
      text: [
        `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
        `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
      ],
      images: ["image28.jpg", "image29.jpg", "image28.jpg"],
    },
    options: [
      { title: "Кладовку", image: "image31.jpg" },
      { title: "Парковку", image: "image30.jpg" },
    ],
    flatNumber: 12,
    project: "Васнецово",
    projectId: 4,
    projectType: "ЖК",
    favored: false,
    finishingIn: false,
    level: 1,
    street: "10 лет Октября",
    district: "Пчкаловский",
    discount: "50%",
    newShapes: true,
    house: "2",
    kitchenSpace: 5.7,
    amount: 2,
  },
  {
    id: 7,
    name: "1-комн.",
    type: "flat",
    status: "booked",
    number: 2,
    entrance: 5,
    rooms: 1,
    price: 4000000,
    finishingPrice: 477000,
    meterPrice: 75000,
    layouts: ["image22.png", "image22.png"],
    space: 16.4,
    degree: 140,
    openDate: "2021-10-03T15:00:00.000+05:00",
    about: {
      title: "Отделка",
      text: [
        `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
        `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
      ],
      images: ["image29.jpg", "image28.jpg", "image29.jpg"],
    },
    options: [
      { title: "Кладовку", image: "image31.jpg" },
      { title: "Парковку", image: "image30.jpg" },
    ],
    flatNumber: 12,
    project: "Васнецово",
    projectId: 4,
    projectType: "ЖК",
    favored: false,
    finishingIn: false,
    level: 1,
    street: "10 лет Октября",
    district: "Пчкаловский",
    discount: "50%",
    newShapes: true,
    house: "2",
    kitchenSpace: 5.7,
    amount: 2,
  },
  {
    id: 8,
    name: "2-комн.",
    type: "flat",
    status: "available",
    number: 3,
    entrance: 5,
    rooms: 2,
    price: 3600000,
    finishingPrice: 507000,
    meterPrice: 75000,
    layouts: ["image23.png", "image22.png"],
    house: "2",
    space: 21.4,
    degree: 0,
    openDate: "2021-10-03T15:00:00.000+05:00",
    about: {
      title: "Отделка",
      text: [
        `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
        `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
      ],
      images: ["image28.jpg", "image29.jpg", "image28.jpg"],
    },
    options: [
      { title: "Кладовку", image: "image31.jpg" },
      { title: "Парковку", image: "image30.jpg" },
    ],
    flatNumber: 12,
    project: "Васнецово",
    projectId: 4,
    projectType: "ЖК",
    favored: false,
    finishingIn: false,
    level: 1,
    street: "10 лет Октября",
    district: "Пчкаловский",
    discount: "50%",
    newShapes: true,
    kitchenSpace: 5.7,
    amount: 2,
  },
  {
    id: 9,
    name: "3-комн.",
    type: "flat",
    status: "sold",
    number: 4,
    entrance: 5,
    rooms: 3,
    price: 4500000,
    finishingPrice: 577000,
    meterPrice: 75000,
    layouts: ["image23.png", "image22.png"],
    space: 40.4,
    degree: 70,
    openDate: "2021-10-03T15:00:00.000+05:00",
    about: {
      title: "Отделка",
      text: [
        `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
        `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
      ],
      images: ["image29.jpg", "image28.jpg", "image29.jpg"],
    },
    options: [
      { title: "Кладовку", image: "image31.jpg" },
      { title: "Парковку", image: "image30.jpg" },
    ],
    flatNumber: 12,
    project: "Васнецово",
    projectId: 4,
    projectType: "ЖК",
    favored: false,
    finishingIn: false,
    level: 1,
    street: "10 лет Октября",
    district: "Пчкаловский",
    discount: "50%",
    newShapes: true,
    house: "2",
    kitchenSpace: 5.7,
    amount: 2,
  },
  {
    id: 10,
    name: "4-комн.",
    type: "flat",
    status: "available",
    number: 5,
    entrance: 5,
    rooms: 4,
    price: 5500000,
    finishingPrice: 577000,
    meterPrice: 75000,
    layouts: ["image23.png", "image22.png"],
    space: 36.4,
    degree: 40,
    openDate: "2021-10-03T15:00:00.000+05:00",
    about: {
      title: "Отделка",
      text: [
        `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
        `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
      ],
      images: ["image28.jpg", "image29.jpg", "image28.jpg"],
    },
    options: [
      { title: "Кладовку", image: "image31.jpg" },
      { title: "Парковку", image: "image30.jpg" },
    ],
    flatNumber: 12,
    project: "Васнецово",
    projectId: 4,
    projectType: "ЖК",
    favored: false,
    finishingIn: false,
    level: 1,
    street: "10 лет Октября",
    district: "Пчкаловский",
    discount: "50%",
    newShapes: true,
    house: "2",
    kitchenSpace: 5.7,
    amount: 2,
  },
  {
    id: 11,
    name: "Студия",
    type: "flat",
    status: "available",
    number: 1,
    entrance: 5,
    rooms: 1,
    price: 4500000,
    finishingPrice: 477000,
    meterPrice: 75000,
    styles: { width: "16%", height: "34%", left: "24%", top: "9%" },
    layouts: ["image21.png", "image22.png"],
    space: 21.4,
    degree: 120,
    openDate: "2021-10-03T15:00:00.000+05:00",
    about: {
      title: "Отделка",
      text: [
        `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
        `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
      ],
      images: ["image28.jpg", "image29.jpg", "image28.jpg"],
    },
    options: [
      { title: "Кладовку", image: "image31.jpg" },
      { title: "Парковку", image: "image30.jpg" },
    ],
    flatNumber: 12,
    project: "Васнецово",
    projectId: 4,
    projectType: "ЖК",
    favored: false,
    finishingIn: false,
    level: 1,
    street: "10 лет Октября",
    district: "Пчкаловский",
    discount: "50%",
    newShapes: true,
    house: "2",
    kitchenSpace: 5.7,
    amount: 2,
  },
  {
    id: 12,
    name: "1-комн.",
    type: "flat",
    status: "available",
    number: 2,
    entrance: 5,
    rooms: 1,
    price: 4000000,
    finishingPrice: 477000,
    meterPrice: 75000,
    layouts: ["image22.png", "image22.png"],
    space: 16.4,
    degree: 140,
    openDate: "2021-10-03T15:00:00.000+05:00",
    about: {
      title: "Отделка",
      text: [
        `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
        `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
      ],
      images: ["image29.jpg", "image28.jpg", "image29.jpg"],
    },
    options: [
      { title: "Кладовку", image: "image31.jpg" },
      { title: "Парковку", image: "image30.jpg" },
    ],
    flatNumber: 12,
    project: "Васнецово",
    projectId: 4,
    projectType: "ЖК",
    favored: false,
    finishingIn: false,
    level: 1,
    street: "10 лет Октября",
    district: "Пчкаловский",
    discount: "50%",
    newShapes: true,
    house: "2",
    kitchenSpace: 5.7,
    amount: 2,
  },
  {
    id: 13,
    name: "2-комн.",
    type: "flat",
    status: "available",
    number: 3,
    entrance: 5,
    rooms: 2,
    price: 3600000,
    finishingPrice: 507000,
    meterPrice: 75000,
    layouts: ["image23.png", "image22.png"],
    house: "2",
    space: 21.4,
    degree: 0,
    openDate: "2021-10-03T15:00:00.000+05:00",
    about: {
      title: "Отделка",
      text: [
        `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
        `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
      ],
      images: ["image28.jpg", "image29.jpg", "image28.jpg"],
    },
    options: [
      { title: "Кладовку", image: "image31.jpg" },
      { title: "Парковку", image: "image30.jpg" },
    ],
    flatNumber: 12,
    project: "Васнецово",
    projectId: 4,
    projectType: "ЖК",
    favored: false,
    finishingIn: false,
    level: 1,
    street: "10 лет Октября",
    district: "Пчкаловский",
    discount: "50%",
    newShapes: true,
    kitchenSpace: 5.7,
    amount: 2,
  },
  {
    id: 14,
    name: "3-комн.",
    type: "flat",
    status: "available",
    number: 4,
    entrance: 5,
    rooms: 3,
    price: 4500000,
    finishingPrice: 577000,
    meterPrice: 75000,
    layouts: ["image23.png", "image22.png"],
    space: 40.4,
    degree: 70,
    openDate: "2021-10-03T15:00:00.000+05:00",
    about: {
      title: "Отделка",
      text: [
        `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
        `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
      ],
      images: ["image29.jpg", "image28.jpg", "image29.jpg"],
    },
    options: [
      { title: "Кладовку", image: "image31.jpg" },
      { title: "Парковку", image: "image30.jpg" },
    ],
    flatNumber: 12,
    project: "Васнецово",
    projectId: 4,
    projectType: "ЖК",
    favored: false,
    finishingIn: false,
    level: 1,
    street: "10 лет Октября",
    district: "Пчкаловский",
    discount: "50%",
    newShapes: true,
    house: "2",
    kitchenSpace: 5.7,
    amount: 2,
  },
  {
    id: 15,
    name: "4-комн.",
    type: "flat",
    status: "available",
    number: 5,
    entrance: 5,
    rooms: 4,
    price: 5500000,
    finishingPrice: 577000,
    meterPrice: 75000,
    layouts: ["image23.png", "image22.png"],
    space: 36.4,
    degree: 40,
    openDate: "2021-10-03T15:00:00.000+05:00",
    about: {
      title: "Отделка",
      text: [
        `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
        `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
      ],
      images: ["image28.jpg", "image29.jpg", "image28.jpg"],
    },
    options: [
      { title: "Кладовку", image: "image31.jpg" },
      { title: "Парковку", image: "image30.jpg" },
    ],
    flatNumber: 12,
    project: "Васнецово",
    projectId: 4,
    projectType: "ЖК",
    favored: false,
    finishingIn: false,
    level: 1,
    street: "10 лет Октября",
    district: "Пчкаловский",
    discount: "50%",
    newShapes: true,
    house: "2",
    kitchenSpace: 5.7,
    amount: 2,
  },
  {
    id: 16,
    name: "Студия",
    type: "flat",
    status: "available",
    number: 1,
    entrance: 5,
    rooms: 1,
    price: 4500000,
    finishingPrice: 477000,
    meterPrice: 75000,
    styles: { width: "16%", height: "34%", left: "24%", top: "9%" },
    layouts: ["image21.png", "image22.png"],
    space: 21.4,
    degree: 120,
    openDate: "2021-10-03T15:00:00.000+05:00",
    about: {
      title: "Отделка",
      text: [
        `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
        `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
      ],
      images: ["image28.jpg", "image29.jpg", "image28.jpg"],
    },
    options: [
      { title: "Кладовку", image: "image31.jpg" },
      { title: "Парковку", image: "image30.jpg" },
    ],
    flatNumber: 12,
    project: "Васнецово",
    projectId: 4,
    projectType: "ЖК",
    favored: false,
    finishingIn: false,
    level: 1,
    street: "10 лет Октября",
    district: "Пчкаловский",
    discount: "50%",
    newShapes: true,
    house: "2",
    kitchenSpace: 5.7,
    amount: 2,
  },
  {
    id: 17,
    name: "1-комн.",
    type: "flat",
    status: "available",
    number: 2,
    entrance: 5,
    rooms: 1,
    price: 4000000,
    finishingPrice: 477000,
    meterPrice: 75000,
    layouts: ["image22.png", "image22.png"],
    space: 16.4,
    degree: 140,
    openDate: "2021-10-03T15:00:00.000+05:00",
    about: {
      title: "Отделка",
      text: [
        `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
        `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
      ],
      images: ["image29.jpg", "image28.jpg", "image29.jpg"],
    },
    options: [
      { title: "Кладовку", image: "image31.jpg" },
      { title: "Парковку", image: "image30.jpg" },
    ],
    flatNumber: 12,
    project: "Васнецово",
    projectId: 4,
    projectType: "ЖК",
    favored: false,
    finishingIn: false,
    level: 1,
    street: "10 лет Октября",
    district: "Пчкаловский",
    discount: "50%",
    newShapes: true,
    house: "2",
    kitchenSpace: 5.7,
    amount: 2,
  },
  {
    id: 18,
    name: "2-комн.",
    type: "flat",
    status: "available",
    number: 3,
    entrance: 5,
    rooms: 2,
    price: 3600000,
    finishingPrice: 507000,
    meterPrice: 75000,
    layouts: ["image23.png", "image22.png"],
    house: "2",
    space: 21.4,
    degree: 0,
    openDate: "2021-10-03T15:00:00.000+05:00",
    about: {
      title: "Отделка",
      text: [
        `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
        `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
      ],
      images: ["image28.jpg", "image29.jpg", "image28.jpg"],
    },
    options: [
      { title: "Кладовку", image: "image31.jpg" },
      { title: "Парковку", image: "image30.jpg" },
    ],
    flatNumber: 12,
    project: "Васнецово",
    projectId: 4,
    projectType: "ЖК",
    favored: false,
    finishingIn: false,
    level: 1,
    street: "10 лет Октября",
    district: "Пчкаловский",
    discount: "50%",
    newShapes: true,
    kitchenSpace: 5.7,
    amount: 2,
  },
  {
    id: 19,
    name: "3-комн.",
    type: "flat",
    status: "available",
    number: 4,
    entrance: 5,
    rooms: 3,
    price: 4500000,
    finishingPrice: 577000,
    meterPrice: 75000,
    layouts: ["image23.png", "image22.png"],
    space: 40.4,
    degree: 70,
    openDate: "2021-10-03T15:00:00.000+05:00",
    about: {
      title: "Отделка",
      text: [
        `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
        `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
      ],
      images: ["image29.jpg", "image28.jpg", "image29.jpg"],
    },
    options: [
      { title: "Кладовку", image: "image31.jpg" },
      { title: "Парковку", image: "image30.jpg" },
    ],
    flatNumber: 12,
    project: "Васнецово",
    projectId: 4,
    projectType: "ЖК",
    favored: false,
    finishingIn: false,
    level: 1,
    street: "10 лет Октября",
    district: "Пчкаловский",
    discount: "50%",
    newShapes: true,
    house: "2",
    kitchenSpace: 5.7,
    amount: 2,
  },
  {
    id: 20,
    name: "4-комн.",
    type: "flat",
    status: "available",
    number: 5,
    entrance: 5,
    rooms: 4,
    price: 5500000,
    finishingPrice: 577000,
    meterPrice: 75000,
    layouts: ["image23.png", "image22.png"],
    space: 36.4,
    degree: 40,
    openDate: "2021-10-03T15:00:00.000+05:00",
    about: {
      title: "Отделка",
      text: [
        `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
        `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
      ],
      images: ["image28.jpg", "image29.jpg", "image28.jpg"],
    },
    options: [
      { title: "Кладовку", image: "image31.jpg" },
      { title: "Парковку", image: "image30.jpg" },
    ],
    flatNumber: 12,
    project: "Васнецово",
    projectId: 4,
    projectType: "ЖК",
    favored: false,
    finishingIn: false,
    level: 1,
    street: "10 лет Октября",
    district: "Пчкаловский",
    discount: "50%",
    newShapes: true,
    house: "2",
    kitchenSpace: 5.7,
    amount: 2,
  },
];

export const levels = [
  [{
    level: -1,
    flats: [
      larders[0],
      larders[1],
      larders[0],
      larders[1],
      larders[0],
      larders[1],
      larders[0],
      larders[1],
    ],
    image: "image27.png",
  },
  {
    level: 1,
    flats: [flats[0], flats[2], flats[4], flats[3], flats[1]],
    image: "image27.png",
  },
  {
    level: 2,
    flats: [flats[0], flats[1], flats[2], flats[3], flats[4]],
    image: "image27.png",
  },
  {
    level: 3,
    flats: [flats[4], flats[1], flats[2], flats[3], flats[0]],
    image: "image27.png",
  },
  {
    level: 4,
    flats: [flats[0], flats[2], flats[1], flats[3], flats[4]],
    image: "image27.png",
  },
  {
    level: 5,
    flats: [flats[1], flats[3], flats[2], flats[0], flats[4]],
    image: "image27.png",
  },
  {
    level: 6,
    flats: [flats[4], flats[2], flats[1], flats[3], flats[0]],
    image: "image27.png",
  },
  {
    level: 7,
    flats: [flats[0], flats[4], flats[3], flats[2], flats[1]],
    image: "image27.png",
  },]
];

export const buildings = [
  {
    id: 1,
    number: "3",
    levels: levels[0],
    parkingImg: "image28.png",
    parkings: [parkings[0], parkings[1], parkings[2], parkings[3], parkings[4], parkings[5]],
    datePic: "2021-10-03T15:00:00.000+05:00",
    images: [
      { image: "image24.png", imageSmall: "image24small.png" },
      { image: "image25.png", imageSmall: "image25small.png" },
      { image: "image26.png", imageSmall: "image26small.png" },
    ],
    styles: {
      clipPath: `polygon(9px 66px, 27px 47px, 2px 24px, 16px 8px, 45px 29px, 73px 1px, 89px 16px, 25px 82px)`,
      width: "31.5%",
      height: "29.5%",
      left: "65%",
      top: "68%",
    },
  },
  {
    id: 2,
    number: "2",
    levels: levels[0],
    parkingImg: "image28.png",
    parkings: [parkings[0], parkings[1], parkings[2], parkings[3], parkings[4], parkings[5]],
    datePic: "2021-12-03T15:00:00.000+05:00",
    images: [
      { image: "image24.png", imageSmall: "image24small.png" },
      { image: "image25.png", imageSmall: "image25small.png" },
      { image: "image26.png", imageSmall: "image26small.png" },
    ],
    styles: {
      clipPath: `polygon(9px 66px, 27px 47px, 2px 24px, 16px 8px, 45px 29px, 73px 1px, 89px 16px, 25px 82px)`,
      width: "31.5%",
      height: "29.5%",
      left: "65%",
      top: "68%",
    },
  },
  {
    id: 3,
    number: "4",
    levels: levels[0],
    parkingImg: "image28.png",
    parkings: [parkings[0], parkings[1], parkings[2], parkings[3], parkings[4], parkings[5]],
    datePic: "2021-12-03T15:00:00.000+05:00",
    images: [
      { image: "image24.png", imageSmall: "image24small.png" },
      { image: "image25.png", imageSmall: "image25small.png" },
      { image: "image26.png", imageSmall: "image26small.png" },
    ],
    styles: {
      clipPath: `polygon(9px 66px, 27px 47px, 2px 24px, 16px 8px, 45px 29px, 73px 1px, 89px 16px, 25px 82px)`,
      width: "31.5%",
      height: "29.5%",
      left: "65%",
      top: "68%",
    },
  },
];

export const Projects = [
  {
    id: 1,
    name: "Forest",
    address: "Ижевск, ул. Союзная",
    type: "ЖК",
    minPrice: 4500000,
    space: 134,
    about: {
      text: [
        `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
        `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
      ],
      images: [
        { image: "image27.jpg", imageSmall: "image27small.jpg" },
        { image: "image26.jpg", imageSmall: "image26small.jpg" },
        { image: "image27.jpg", imageSmall: "image27small.jpg" },
      ],
    },
    location: [55.684758, 37.738521],
    nearerObjects: [
      {
        id: 1,
        location: [55.684758, 37.738521],
        type: "culture",
        title: "Театр",
        infoLeft: "1060 мест",
        infoRight: "с 1960г",
      },
      {
        id: 2,
        location: [55.684758, 37.738521],
        type: "medicine",
        title: "поликлиника",
        infoLeft: "Лотос",
      },
      {
        id: 3,
        location: [55.684758, 37.738521],
        type: "education",
        title: "Школа",
        infoLeft: "1060 мест",
        infoRight: "Сдан",
      },
      {
        id: 4,
        location: [55.684758, 37.738521],
        type: "shop",
        title: "Магазины",
        infoLeft: "Reserved, Cropp, Zara",
      },
      {
        id: 5,
        location: [55.684758, 37.738521],
        type: "food",
        title: "Семейный ресторан",
        infoLeft: "Своя компания",
        infoRight: "₽₽",
      },
      {
        id: 6,
        location: [55.684758, 37.738521],
        type: "sport",
        title: "Спортзал",
      },
      {
        id: 7,
        location: [55.684758, 37.738521],
        type: "transport",
        title: "Метро",
        infoLeft: "Остановка 'Достоевская'",
      },
      {
        id: 8,
        location: [55.684758, 37.738521],
        type: "kindergarten",
        title: "Детский сад",
        infoLeft: "400 мест",
        infoRight: "Сдан",
      },
    ],
    district: "Ульяновский",
    openDate: "2017-05-15T08:30:00.000+05:00",
    image: { image: "image13.png", imageSmall: "image13small.png" },
    images: [
      { image: "image13.png", imageSmall: "image13small.png" },
      { image: "image13.png", imageSmall: "image13small.png" },
      { image: "image13.png", imageSmall: "image13small.png" },
    ],
    genLayout: "svg1.svg",
    buildings: [ buildings[0], buildings[1], buildings[2], buildings[2] ],
    discount: "10%",
    newShapes: true,
    flats: [
      {
        id: 2,
        name: "1-комн.",
        type: 1,
        price: 4000000,
        amount: 3,
      },
      {
        id: 4,
        name: "2-комн.",
        type: 2,
        price: 3000000,
        amount: 1,
      },
      {
        id: 5,
        name: "3-комн.",
        type: 3,
        price: 3500000,
        amount: 12,
      },
    ],
  },
  {
    id: 2,
    name: "Forest",
    address: "Ижевск, ул. Союзная",
    type: "ЖК",
    minPrice: 4000000,
    space: 134,
    about: {
      text: [
        `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
        `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
      ],
      images: [
        { image: "image27.jpg", imageSmall: "image27small.jpg" },
        { image: "image26.jpg", imageSmall: "image26small.jpg" },
        { image: "image27.jpg", imageSmall: "image27small.jpg" },
      ],
    },
    location: [55.833436, 37.715175],
    nearerObjects: [
      {
        id: 1,
        location: [55.833436, 37.715175],
        type: "culture",
        title: "Театр",
        infoLeft: "1060 мест",
        infoRight: "с 1960г",
      },
      {
        id: 2,
        location: [55.833436, 37.715175],
        type: "medicine",
        title: "поликлиника",
        infoLeft: "Лотос",
      },
      {
        id: 3,
        location: [55.833436, 37.715175],
        type: "education",
        title: "Школа",
        infoLeft: "1060 мест",
        infoRight: "Сдан",
      },
      {
        id: 4,
        location: [55.833436, 37.715175],
        type: "shop",
        title: "Магазины",
        infoLeft: "Reserved, Cropp, Zara",
      },
      {
        id: 5,
        location: [55.833436, 37.715175],
        type: "food",
        title: "Семейный ресторан",
        infoLeft: "Своя компания",
        infoRight: "₽₽",
      },
      {
        id: 6,
        location: [55.833436, 37.715175],
        type: "sport",
        title: "Спортзал",
      },
      {
        id: 7,
        location: [55.833436, 37.715175],
        type: "transport",
        title: "Метро",
        infoLeft: "Остановка 'Достоевская'",
      },
      {
        id: 8,
        location: [55.833436, 37.715175],
        type: "kindergarten",
        title: "Детский сад",
        infoLeft: "400 мест",
        infoRight: "Сдан",
      },
    ],
    district: "Ульяновский",
    openDate: "2028-08-10T12:00:00.000+05:00",
    image: { image: "image16.png", imageSmall: "image16small.png" },
    images: [
      { image: "image16.png", imageSmall: "image16small.png" },
      { image: "image16.png", imageSmall: "image16small.png" },
      { image: "image16.png", imageSmall: "image16small.png" },
    ],
    genLayout: "svg1.svg",
    buildings: [ buildings[0], buildings[1], buildings[2] ],
    discount: "50%",
    newShapes: true,
    flats: [
      {
        id: 2,
        name: "1-комн.",
        type: 1,
        price: 4000000,
        amount: 3,
      },
    ],
  },
  {
    id: 3,
    name: "Плюс один",
    address: "Ижевск, ул. Союзная",
    type: "ЖК",
    minPrice: 3000000,
    space: 134,
    about: {
      text: [
        `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
        `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
      ],
      images: [
        { image: "image27.jpg", imageSmall: "image27small.jpg" },
        { image: "image26.jpg", imageSmall: "image26small.jpg" },
        { image: "image27.jpg", imageSmall: "image27small.jpg" },
      ],
    },
    location: [55.687086, 37.529789],
    nearerObjects: [
      {
        id: 1,
        location: [55.687086, 37.529789],
        type: "culture",
        title: "Театр",
        infoLeft: "1060 мест",
        infoRight: "с 1960г",
      },
      {
        id: 2,
        location: [55.687086, 37.529789],
        type: "medicine",
        title: "поликлиника",
        infoLeft: "Лотос",
      },
      {
        id: 3,
        location: [55.687086, 37.529789],
        type: "education",
        title: "Школа",
        infoLeft: "1060 мест",
        infoRight: "Сдан",
      },
      {
        id: 4,
        location: [55.687086, 37.529789],
        type: "shop",
        title: "Магазины",
        infoLeft: "Reserved, Cropp, Zara",
      },
      {
        id: 5,
        location: [55.687086, 37.529789],
        type: "food",
        title: "Семейный ресторан",
        infoLeft: "Своя компания",
        infoRight: "₽₽",
      },
      {
        id: 6,
        location: [55.687086, 37.529789],
        type: "sport",
        title: "Спортзал",
      },
      {
        id: 7,
        location: [55.687086, 37.529789],
        type: "transport",
        title: "Метро",
        infoLeft: "Остановка 'Достоевская'",
      },
      {
        id: 8,
        location: [55.687086, 37.529789],
        type: "kindergarten",
        title: "Детский сад",
        infoLeft: "400 мест",
        infoRight: "Сдан",
      },
    ],
    district: "Ульяновский",
    openDate: "2021-02-20T15:00:00.000+05:00",
    image: { image: "image17.png", imageSmall: "image17small.png" },
    images: [
      { image: "image17.png", imageSmall: "image17small.png" },
      { image: "image17.png", imageSmall: "image17small.png" },
      { image: "image17.png", imageSmall: "image17small.png" },
    ],
    genLayout: "svg1.svg",
    buildings: [ buildings[0], buildings[1], buildings[2] ],
    newShapes: true,
    flats: [
      {
        id: 1,
        name: "Студия",
        type: 0,
        price: 4500000,
        amount: 2,
      },
      {
        id: 2,
        name: "1-комн.",
        type: 1,
        price: 4000000,
        amount: 3,
      },
    ],
  },
  {
    id: 4,
    name: "Васнецово",
    address: "Ижевск, ул. Танкограда",
    type: "ЖК",
    minPrice: 4200000,
    space: 134,
    about: {
      text: [
        `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
        `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
      ],
      images: [
        { image: "image27.jpg", imageSmall: "image27small.jpg" },
        { image: "image26.jpg", imageSmall: "image26small.jpg" },
        { image: "image27.jpg", imageSmall: "image27small.jpg" },
      ],
    },
    location: [55.782392, 37.611724],
    nearerObjects: [
      {
        id: 1,
        location: [55.782602, 37.614034],
        type: "culture",
        title: "Театр",
        infoLeft: "1060 мест",
        infoRight: "с 1960г",
      },
      {
        id: 2,
        location: [55.782192, 37.611524],
        type: "medicine",
        title: "поликлиника",
        infoLeft: "Лотос",
      },
      {
        id: 3,
        location: [55.782182, 37.611834],
        type: "education",
        title: "Школа",
        infoLeft: "1060 мест",
        infoRight: "Сдан",
      },
      {
        id: 4,
        location: [55.782082, 37.611934],
        type: "shop",
        title: "Магазины",
        infoLeft: "Reserved, Cropp, Zara",
      },
      {
        id: 5,
        location: [55.782882, 37.610834],
        type: "food",
        title: "Семейный ресторан",
        infoLeft: "Своя компания",
        infoRight: "₽₽",
      },
      {
        id: 6,
        location: [55.782582, 37.612834],
        type: "sport",
        title: "Спортзал",
      },
      {
        id: 7,
        location: [55.782452, 37.612634],
        type: "transport",
        title: "Метро",
        infoLeft: "Остановка 'Достоевская'",
      },
      {
        id: 8,
        location: [55.7823, 37.611934],
        type: "kindergarten",
        title: "Детский сад",
        infoLeft: "400 мест",
        infoRight: "Сдан",
      },
    ],
    district: "Пчкаловский",
    openDate: "2021-10-03T15:00:00.000+05:00",
    image: { image: "image27.jpg", imageSmall: "image27small.jpg" },
    images: [
      { image: "image27.jpg", imageSmall: "image27small.jpg" },
      { image: "image27.jpg", imageSmall: "image27small.jpg" },
      { image: "image27.jpg", imageSmall: "image27small.jpg" },
    ],
    genLayout: "svg1.svg",
    buildings: [ buildings[0], buildings[1], buildings[2] ],
    discount: "10%",
    newShapes: true,
    flats: [
      {
        id: 1,
        name: "Студия",
        type: 0,
        price: 4500000,
        amount: 2,
      },
      {
        id: 2,
        name: "1-комн.",
        type: 1,
        price: 4000000,
        amount: 3,
      },
      {
        id: 4,
        name: "2-комн.",
        type: 2,
        price: 3000000,
        amount: 1,
      },
      {
        id: 5,
        name: "3-комн.",
        type: 3,
        price: 3500000,
        amount: 12,
      },
      {
        id: 6,
        name: "4-комн.",
        type: 3,
        price: 4500000,
        amount: 12,
      },
    ],
  },
  {
    id: 5,
    name: "ARTNOVA",
    address: "Ижевск, ул. Великая",
    type: "ЖК",
    minPrice: 6500000,
    space: 134,
    about: {
      text: [
        `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
        `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
      ],
      images: [
        { image: "image27.jpg", imageSmall: "image27small.jpg" },
        { image: "image26.jpg", imageSmall: "image26small.jpg" },
        { image: "image27.jpg", imageSmall: "image27small.jpg" },
      ],
    },
    location: [55.642063, 37.656123],
    nearerObjects: [
      {
        id: 1,
        location: [55.642063, 37.656123],
        type: "culture",
        title: "Театр",
        infoLeft: "1060 мест",
        infoRight: "с 1960г",
      },
      {
        id: 2,
        location: [55.642063, 37.656123],
        type: "medicine",
        title: "поликлиника",
        infoLeft: "Лотос",
      },
      {
        id: 3,
        location: [55.642063, 37.656123],
        type: "education",
        title: "Школа",
        infoLeft: "1060 мест",
        infoRight: "Сдан",
      },
      {
        id: 4,
        location: [55.642063, 37.656123],
        type: "shop",
        title: "Магазины",
        infoLeft: "Reserved, Cropp, Zara",
      },
      {
        id: 5,
        location: [55.642063, 37.656123],
        type: "food",
        title: "Семейный ресторан",
        infoLeft: "Своя компания",
        infoRight: "₽₽",
      },
      {
        id: 6,
        location: [55.642063, 37.656123],
        type: "sport",
        title: "Спортзал",
      },
      {
        id: 7,
        location: [55.642063, 37.656123],
        type: "transport",
        title: "Метро",
        infoLeft: "Остановка 'Достоевская'",
      },
      {
        id: 8,
        location: [55.642063, 37.656123],
        type: "kindergarten",
        title: "Детский сад",
        infoLeft: "400 мест",
        infoRight: "Сдан",
      },
    ],
    district: "Стоический",
    openDate: "2022-04-11T15:00:00.000+05:00",
    image: { image: "image18.png", imageSmall: "image18small.png" },
    images: [
      { image: "image18.png", imageSmall: "image18small.png" },
      { image: "image18.png", imageSmall: "image18small.png" },
      { image: "image18.png", imageSmall: "image18small.png" },
    ],
    genLayout: "svg1.svg",
    buildings: [ buildings[0], buildings[1], buildings[2] ],
    newShapes: true,
    flats: [
      {
        id: 2,
        name: "1-комн.",
        type: 1,
        price: 4000000,
        amount: 3,
      },
      {
        id: 4,
        name: "2-комн.",
        type: 2,
        price: 3000000,
        amount: 1,
      },
      {
        id: 5,
        name: "3-комн.",
        type: 3,
        price: 3500000,
        amount: 12,
      },
    ],
  },
  {
    id: 6,
    name: "Плюс один",
    address: "Ижевск, ул. Великая",
    type: "ЖК",
    minPrice: 3500000,
    space: 131,
    about: {
      text: [
        `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
        `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
      ],
      images: [
        { image: "image27.jpg", imageSmall: "image27small.jpg" },
        { image: "image26.jpg", imageSmall: "image26small.jpg" },
        { image: "image27.jpg", imageSmall: "image27small.jpg" },
      ],
    },
    location: [55.826479, 37.487208],
    nearerObjects: [
      {
        id: 1,
        location: [55.826479, 37.487208],
        type: "culture",
        title: "Театр",
        infoLeft: "1060 мест",
        infoRight: "с 1960г",
      },
      {
        id: 2,
        location: [55.826479, 37.487208],
        type: "medicine",
        title: "поликлиника",
        infoLeft: "Лотос",
      },
      {
        id: 3,
        location: [55.826479, 37.487208],
        type: "education",
        title: "Школа",
        infoLeft: "1060 мест",
        infoRight: "Сдан",
      },
      {
        id: 4,
        location: [55.826479, 37.487208],
        type: "shop",
        title: "Магазины",
        infoLeft: "Reserved, Cropp, Zara",
      },
      {
        id: 5,
        location: [55.826479, 37.487208],
        type: "food",
        title: "Семейный ресторан",
        infoLeft: "Своя компания",
        infoRight: "₽₽",
      },
      {
        id: 6,
        location: [55.826479, 37.487208],
        type: "sport",
        title: "Спортзал",
      },
      {
        id: 7,
        location: [55.826479, 37.487208],
        type: "transport",
        title: "Метро",
        infoLeft: "Остановка 'Достоевская'",
      },
      {
        id: 8,
        location: [55.826479, 37.487208],
        type: "kindergarten",
        title: "Детский сад",
        infoLeft: "400 мест",
        infoRight: "Сдан",
      },
    ],
    district: "Стоический",
    openDate: "2025-12-12T15:00:00.000+05:00",
    image: { image: "image19.png", imageSmall: "image19small.png" },
    images: [
      { image: "image19.png", imageSmall: "image19small.png" },
      { image: "image19.png", imageSmall: "image19small.png" },
      { image: "image19.png", imageSmall: "image19small.png" },
    ],
    genLayout: "svg1.svg",
    buildings: [ buildings[0], buildings[1], buildings[2] ],
    newShapes: true,
    flats: [
      {
        id: 2,
        name: "1-комн.",
        type: 1,
        price: 4000000,
        amount: 3,
      },
      {
        id: 4,
        name: "2-комн.",
        type: 2,
        price: 3000000,
        amount: 1,
      },
      {
        id: 5,
        name: "3-комн.",
        type: 3,
        price: 3500000,
        amount: 12,
      },
    ],
  },
  {
    id: 7,
    name: "Forest1",
    address: "Ижевск, ул. Союзная",
    type: "ЖК",
    minPrice: 4500000,
    space: 134,
    about: {
      text: [
        `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
        `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
      ],
      images: [
        { image: "image27.jpg", imageSmall: "image27small.jpg" },
        { image: "image26.jpg", imageSmall: "image26small.jpg" },
        { image: "image27.jpg", imageSmall: "image27small.jpg" },
      ],
    },
    location: [55.684958, 37.738521],
    nearerObjects: [
      {
        id: 1,
        location: [55.684758, 37.738521],
        type: "culture",
        title: "Театр",
        infoLeft: "1060 мест",
        infoRight: "с 1960г",
      },
      {
        id: 2,
        location: [55.684758, 37.738521],
        type: "medicine",
        title: "поликлиника",
        infoLeft: "Лотос",
      },
      {
        id: 3,
        location: [55.684758, 37.738521],
        type: "education",
        title: "Школа",
        infoLeft: "1060 мест",
        infoRight: "Сдан",
      },
      {
        id: 4,
        location: [55.684758, 37.738521],
        type: "shop",
        title: "Магазины",
        infoLeft: "Reserved, Cropp, Zara",
      },
      {
        id: 5,
        location: [55.684758, 37.738521],
        type: "food",
        title: "Семейный ресторан",
        infoLeft: "Своя компания",
        infoRight: "₽₽",
      },
      {
        id: 6,
        location: [55.684758, 37.738521],
        type: "sport",
        title: "Спортзал",
      },
      {
        id: 7,
        location: [55.684758, 37.738521],
        type: "transport",
        title: "Метро",
        infoLeft: "Остановка 'Достоевская'",
      },
      {
        id: 8,
        location: [55.684758, 37.738521],
        type: "kindergarten",
        title: "Детский сад",
        infoLeft: "400 мест",
        infoRight: "Сдан",
      },
    ],
    district: "Ульяновский",
    openDate: "2017-05-15T08:30:00.000+05:00",
    image: { image: "image13.png", imageSmall: "image13small.png" },
    images: [
      { image: "image13.png", imageSmall: "image13small.png" },
      { image: "image13.png", imageSmall: "image13small.png" },
      { image: "image13.png", imageSmall: "image13small.png" },
    ],
    genLayout: "svg1.svg",
    buildings: [ buildings[0], buildings[1], buildings[2], buildings[2] ],
    discount: "10%",
    newShapes: true,
    flats: [
      {
        id: 2,
        name: "1-комн.",
        type: 1,
        price: 4000000,
        amount: 3,
      },
      {
        id: 4,
        name: "2-комн.",
        type: 2,
        price: 3000000,
        amount: 1,
      },
      {
        id: 5,
        name: "3-комн.",
        type: 3,
        price: 3500000,
        amount: 12,
      },
    ],
  },
  {
    id: 8,
    name: "Forest2",
    address: "Ижевск, ул. Союзная",
    type: "ЖК",
    minPrice: 4000000,
    space: 134,
    about: {
      text: [
        `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
        `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
      ],
      images: [
        { image: "image27.jpg", imageSmall: "image27small.jpg" },
        { image: "image26.jpg", imageSmall: "image26small.jpg" },
        { image: "image27.jpg", imageSmall: "image27small.jpg" },
      ],
    },
    location: [55.833436, 37.715275],
    nearerObjects: [
      {
        id: 1,
        location: [55.833436, 37.715175],
        type: "culture",
        title: "Театр",
        infoLeft: "1060 мест",
        infoRight: "с 1960г",
      },
      {
        id: 2,
        location: [55.833436, 37.715175],
        type: "medicine",
        title: "поликлиника",
        infoLeft: "Лотос",
      },
      {
        id: 3,
        location: [55.833436, 37.715175],
        type: "education",
        title: "Школа",
        infoLeft: "1060 мест",
        infoRight: "Сдан",
      },
      {
        id: 4,
        location: [55.833436, 37.715175],
        type: "shop",
        title: "Магазины",
        infoLeft: "Reserved, Cropp, Zara",
      },
      {
        id: 5,
        location: [55.833436, 37.715175],
        type: "food",
        title: "Семейный ресторан",
        infoLeft: "Своя компания",
        infoRight: "₽₽",
      },
      {
        id: 6,
        location: [55.833436, 37.715175],
        type: "sport",
        title: "Спортзал",
      },
      {
        id: 7,
        location: [55.833436, 37.715175],
        type: "transport",
        title: "Метро",
        infoLeft: "Остановка 'Достоевская'",
      },
      {
        id: 8,
        location: [55.833436, 37.715175],
        type: "kindergarten",
        title: "Детский сад",
        infoLeft: "400 мест",
        infoRight: "Сдан",
      },
    ],
    district: "Ульяновский",
    openDate: "2028-08-10T12:00:00.000+05:00",
    image: { image: "image16.png", imageSmall: "image16small.png" },
    images: [
      { image: "image16.png", imageSmall: "image16small.png" },
      { image: "image16.png", imageSmall: "image16small.png" },
      { image: "image16.png", imageSmall: "image16small.png" },
    ],
    genLayout: "svg1.svg",
    buildings: [ buildings[0], buildings[1], buildings[2] ],
    discount: "50%",
    newShapes: true,
    flats: [
      {
        id: 2,
        name: "1-комн.",
        type: 1,
        price: 4000000,
        amount: 3,
      },
    ],
  },
  {
    id: 9,
    name: "Плюс два",
    address: "Ижевск, ул. Союзная",
    type: "ЖК",
    minPrice: 3000000,
    space: 134,
    about: {
      text: [
        `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
        `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
      ],
      images: [
        { image: "image27.jpg", imageSmall: "image27small.jpg" },
        { image: "image26.jpg", imageSmall: "image26small.jpg" },
        { image: "image27.jpg", imageSmall: "image27small.jpg" },
      ],
    },
    location: [55.687086, 37.529653],
    nearerObjects: [
      {
        id: 1,
        location: [55.687086, 37.529789],
        type: "culture",
        title: "Театр",
        infoLeft: "1060 мест",
        infoRight: "с 1960г",
      },
      {
        id: 2,
        location: [55.687086, 37.529789],
        type: "medicine",
        title: "поликлиника",
        infoLeft: "Лотос",
      },
      {
        id: 3,
        location: [55.687086, 37.529789],
        type: "education",
        title: "Школа",
        infoLeft: "1060 мест",
        infoRight: "Сдан",
      },
      {
        id: 4,
        location: [55.687086, 37.529789],
        type: "shop",
        title: "Магазины",
        infoLeft: "Reserved, Cropp, Zara",
      },
      {
        id: 5,
        location: [55.687086, 37.529789],
        type: "food",
        title: "Семейный ресторан",
        infoLeft: "Своя компания",
        infoRight: "₽₽",
      },
      {
        id: 6,
        location: [55.687086, 37.529789],
        type: "sport",
        title: "Спортзал",
      },
      {
        id: 7,
        location: [55.687086, 37.529789],
        type: "transport",
        title: "Метро",
        infoLeft: "Остановка 'Достоевская'",
      },
      {
        id: 8,
        location: [55.687086, 37.529789],
        type: "kindergarten",
        title: "Детский сад",
        infoLeft: "400 мест",
        infoRight: "Сдан",
      },
    ],
    district: "Ульяновский",
    openDate: "2021-02-20T15:00:00.000+05:00",
    image: { image: "image17.png", imageSmall: "image17small.png" },
    images: [
      { image: "image17.png", imageSmall: "image17small.png" },
      { image: "image17.png", imageSmall: "image17small.png" },
      { image: "image17.png", imageSmall: "image17small.png" },
    ],
    genLayout: "svg1.svg",
    buildings: [ buildings[0], buildings[1], buildings[2] ],
    newShapes: true,
    flats: [
      {
        id: 1,
        name: "Студия",
        type: 0,
        price: 4500000,
        amount: 2,
      },
      {
        id: 2,
        name: "1-комн.",
        type: 1,
        price: 4000000,
        amount: 3,
      },
    ],
  },
  {
    id: 10,
    name: "Васнецово1",
    address: "Ижевск, ул. Танкограда",
    type: "ЖК",
    minPrice: 4200000,
    space: 134,
    about: {
      text: [
        `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
        `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
      ],
      images: [
        { image: "image27.jpg", imageSmall: "image27small.jpg" },
        { image: "image26.jpg", imageSmall: "image26small.jpg" },
        { image: "image27.jpg", imageSmall: "image27small.jpg" },
      ],
    },
    location: [55.782592, 37.611224],
    nearerObjects: [
      {
        id: 1,
        location: [55.782602, 37.614034],
        type: "culture",
        title: "Театр",
        infoLeft: "1060 мест",
        infoRight: "с 1960г",
      },
      {
        id: 2,
        location: [55.782192, 37.611524],
        type: "medicine",
        title: "поликлиника",
        infoLeft: "Лотос",
      },
      {
        id: 3,
        location: [55.782182, 37.611834],
        type: "education",
        title: "Школа",
        infoLeft: "1060 мест",
        infoRight: "Сдан",
      },
      {
        id: 4,
        location: [55.782082, 37.611934],
        type: "shop",
        title: "Магазины",
        infoLeft: "Reserved, Cropp, Zara",
      },
      {
        id: 5,
        location: [55.782882, 37.610834],
        type: "food",
        title: "Семейный ресторан",
        infoLeft: "Своя компания",
        infoRight: "₽₽",
      },
      {
        id: 6,
        location: [55.782582, 37.612834],
        type: "sport",
        title: "Спортзал",
      },
      {
        id: 7,
        location: [55.782452, 37.612634],
        type: "transport",
        title: "Метро",
        infoLeft: "Остановка 'Достоевская'",
      },
      {
        id: 8,
        location: [55.7823, 37.611934],
        type: "kindergarten",
        title: "Детский сад",
        infoLeft: "400 мест",
        infoRight: "Сдан",
      },
    ],
    district: "Пчкаловский",
    openDate: "2021-10-03T15:00:00.000+05:00",
    image: { image: "image27.jpg", imageSmall: "image27small.jpg" },
    images: [
      { image: "image27.jpg", imageSmall: "image27small.jpg" },
      { image: "image27.jpg", imageSmall: "image27small.jpg" },
      { image: "image27.jpg", imageSmall: "image27small.jpg" },
    ],
    genLayout: "svg1.svg",
    buildings: [ buildings[0], buildings[1], buildings[2] ],
    discount: "10%",
    newShapes: true,
    flats: [
      {
        id: 1,
        name: "Студия",
        type: 0,
        price: 4500000,
        amount: 2,
      },
      {
        id: 2,
        name: "1-комн.",
        type: 1,
        price: 4000000,
        amount: 3,
      },
      {
        id: 4,
        name: "2-комн.",
        type: 2,
        price: 3000000,
        amount: 1,
      },
      {
        id: 5,
        name: "3-комн.",
        type: 3,
        price: 3500000,
        amount: 12,
      },
      {
        id: 6,
        name: "4-комн.",
        type: 3,
        price: 4500000,
        amount: 12,
      },
    ],
  },
  {
    id: 11,
    name: "ARTNOVA1",
    address: "Ижевск, ул. Великая",
    type: "ЖК",
    minPrice: 6500000,
    space: 134,
    about: {
      text: [
        `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
        `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
      ],
      images: [
        { image: "image27.jpg", imageSmall: "image27small.jpg" },
        { image: "image26.jpg", imageSmall: "image26small.jpg" },
        { image: "image27.jpg", imageSmall: "image27small.jpg" },
      ],
    },
    location: [55.642163, 37.656723],
    nearerObjects: [
      {
        id: 1,
        location: [55.642063, 37.656123],
        type: "culture",
        title: "Театр",
        infoLeft: "1060 мест",
        infoRight: "с 1960г",
      },
      {
        id: 2,
        location: [55.642063, 37.656123],
        type: "medicine",
        title: "поликлиника",
        infoLeft: "Лотос",
      },
      {
        id: 3,
        location: [55.642063, 37.656123],
        type: "education",
        title: "Школа",
        infoLeft: "1060 мест",
        infoRight: "Сдан",
      },
      {
        id: 4,
        location: [55.642063, 37.656123],
        type: "shop",
        title: "Магазины",
        infoLeft: "Reserved, Cropp, Zara",
      },
      {
        id: 5,
        location: [55.642063, 37.656123],
        type: "food",
        title: "Семейный ресторан",
        infoLeft: "Своя компания",
        infoRight: "₽₽",
      },
      {
        id: 6,
        location: [55.642063, 37.656123],
        type: "sport",
        title: "Спортзал",
      },
      {
        id: 7,
        location: [55.642063, 37.656123],
        type: "transport",
        title: "Метро",
        infoLeft: "Остановка 'Достоевская'",
      },
      {
        id: 8,
        location: [55.642063, 37.656123],
        type: "kindergarten",
        title: "Детский сад",
        infoLeft: "400 мест",
        infoRight: "Сдан",
      },
    ],
    district: "Стоический",
    openDate: "2022-04-11T15:00:00.000+05:00",
    image: { image: "image18.png", imageSmall: "image18small.png" },
    images: [
      { image: "image18.png", imageSmall: "image18small.png" },
      { image: "image18.png", imageSmall: "image18small.png" },
      { image: "image18.png", imageSmall: "image18small.png" },
    ],
    genLayout: "svg1.svg",
    buildings: [ buildings[0], buildings[1], buildings[2] ],
    newShapes: true,
    flats: [
      {
        id: 2,
        name: "1-комн.",
        type: 1,
        price: 4000000,
        amount: 3,
      },
      {
        id: 4,
        name: "2-комн.",
        type: 2,
        price: 3000000,
        amount: 1,
      },
      {
        id: 5,
        name: "3-комн.",
        type: 3,
        price: 3500000,
        amount: 12,
      },
    ],
  },
  {
    id: 12,
    name: "Плюс один",
    address: "Ижевск, ул. Великая",
    type: "ЖК",
    minPrice: 3500000,
    space: 131,
    about: {
      text: [
        `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
        `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
      ],
      images: [
        { image: "image27.jpg", imageSmall: "image27small.jpg" },
        { image: "image26.jpg", imageSmall: "image26small.jpg" },
        { image: "image27.jpg", imageSmall: "image27small.jpg" },
      ],
    },
    location: [55.826179, 37.487708],
    nearerObjects: [
      {
        id: 1,
        location: [55.826479, 37.487208],
        type: "culture",
        title: "Театр",
        infoLeft: "1060 мест",
        infoRight: "с 1960г",
      },
      {
        id: 2,
        location: [55.826479, 37.487208],
        type: "medicine",
        title: "поликлиника",
        infoLeft: "Лотос",
      },
      {
        id: 3,
        location: [55.826479, 37.487208],
        type: "education",
        title: "Школа",
        infoLeft: "1060 мест",
        infoRight: "Сдан",
      },
      {
        id: 4,
        location: [55.826479, 37.487208],
        type: "shop",
        title: "Магазины",
        infoLeft: "Reserved, Cropp, Zara",
      },
      {
        id: 5,
        location: [55.826479, 37.487208],
        type: "food",
        title: "Семейный ресторан",
        infoLeft: "Своя компания",
        infoRight: "₽₽",
      },
      {
        id: 6,
        location: [55.826479, 37.487208],
        type: "sport",
        title: "Спортзал",
      },
      {
        id: 7,
        location: [55.826479, 37.487208],
        type: "transport",
        title: "Метро",
        infoLeft: "Остановка 'Достоевская'",
      },
      {
        id: 8,
        location: [55.826479, 37.487208],
        type: "kindergarten",
        title: "Детский сад",
        infoLeft: "400 мест",
        infoRight: "Сдан",
      },
    ],
    district: "Стоический",
    openDate: "2025-12-12T15:00:00.000+05:00",
    image: { image: "image19.png", imageSmall: "image19small.png" },
    images: [
      { image: "image19.png", imageSmall: "image19small.png" },
      { image: "image19.png", imageSmall: "image19small.png" },
      { image: "image19.png", imageSmall: "image19small.png" },
    ],
    genLayout: "svg1.svg",
    buildings: [ buildings[0], buildings[1], buildings[2] ],
    newShapes: true,
    flats: [
      {
        id: 2,
        name: "1-комн.",
        type: 1,
        price: 4000000,
        amount: 3,
      },
      {
        id: 4,
        name: "2-комн.",
        type: 2,
        price: 3000000,
        amount: 1,
      },
      {
        id: 5,
        name: "3-комн.",
        type: 3,
        price: 3500000,
        amount: 12,
      },
    ],
  },
  {
    id: 13,
    name: "Васнецово1",
    address: "Ижевск, ул. Танкограда",
    type: "ЖК",
    minPrice: 4200000,
    space: 134,
    about: {
      text: [
        `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
        `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
      ],
      images: [
        { image: "image27.jpg", imageSmall: "image27small.jpg" },
        { image: "image26.jpg", imageSmall: "image26small.jpg" },
        { image: "image27.jpg", imageSmall: "image27small.jpg" },
      ],
    },
    location: [55.782592, 37.611224],
    nearerObjects: [
      {
        id: 1,
        location: [55.782602, 37.614034],
        type: "culture",
        title: "Театр",
        infoLeft: "1060 мест",
        infoRight: "с 1960г",
      },
      {
        id: 2,
        location: [55.782192, 37.611524],
        type: "medicine",
        title: "поликлиника",
        infoLeft: "Лотос",
      },
      {
        id: 3,
        location: [55.782182, 37.611834],
        type: "education",
        title: "Школа",
        infoLeft: "1060 мест",
        infoRight: "Сдан",
      },
      {
        id: 4,
        location: [55.782082, 37.611934],
        type: "shop",
        title: "Магазины",
        infoLeft: "Reserved, Cropp, Zara",
      },
      {
        id: 5,
        location: [55.782882, 37.610834],
        type: "food",
        title: "Семейный ресторан",
        infoLeft: "Своя компания",
        infoRight: "₽₽",
      },
      {
        id: 6,
        location: [55.782582, 37.612834],
        type: "sport",
        title: "Спортзал",
      },
      {
        id: 7,
        location: [55.782452, 37.612634],
        type: "transport",
        title: "Метро",
        infoLeft: "Остановка 'Достоевская'",
      },
      {
        id: 8,
        location: [55.7823, 37.611934],
        type: "kindergarten",
        title: "Детский сад",
        infoLeft: "400 мест",
        infoRight: "Сдан",
      },
    ],
    district: "Пчкаловский",
    openDate: "2021-10-03T15:00:00.000+05:00",
    image: { image: "image27.jpg", imageSmall: "image27small.jpg" },
    images: [
      { image: "image27.jpg", imageSmall: "image27small.jpg" },
      { image: "image27.jpg", imageSmall: "image27small.jpg" },
      { image: "image27.jpg", imageSmall: "image27small.jpg" },
    ],
    genLayout: "svg1.svg",
    buildings: [ buildings[0], buildings[1], buildings[2] ],
    discount: "10%",
    newShapes: true,
    flats: [
      {
        id: 1,
        name: "Студия",
        type: 0,
        price: 4500000,
        amount: 2,
      },
      {
        id: 2,
        name: "1-комн.",
        type: 1,
        price: 4000000,
        amount: 3,
      },
      {
        id: 4,
        name: "2-комн.",
        type: 2,
        price: 3000000,
        amount: 1,
      },
      {
        id: 5,
        name: "3-комн.",
        type: 3,
        price: 3500000,
        amount: 12,
      },
      {
        id: 6,
        name: "4-комн.",
        type: 3,
        price: 4500000,
        amount: 12,
      },
    ],
  },
  {
    id: 14,
    name: "ARTNOVA1",
    address: "Ижевск, ул. Великая",
    type: "ЖК",
    minPrice: 6500000,
    space: 134,
    about: {
      text: [
        `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
        `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
      ],
      images: [
        { image: "image27.jpg", imageSmall: "image27small.jpg" },
        { image: "image26.jpg", imageSmall: "image26small.jpg" },
        { image: "image27.jpg", imageSmall: "image27small.jpg" },
      ],
    },
    location: [55.642163, 37.656723],
    nearerObjects: [
      {
        id: 1,
        location: [55.642063, 37.656123],
        type: "culture",
        title: "Театр",
        infoLeft: "1060 мест",
        infoRight: "с 1960г",
      },
      {
        id: 2,
        location: [55.642063, 37.656123],
        type: "medicine",
        title: "поликлиника",
        infoLeft: "Лотос",
      },
      {
        id: 3,
        location: [55.642063, 37.656123],
        type: "education",
        title: "Школа",
        infoLeft: "1060 мест",
        infoRight: "Сдан",
      },
      {
        id: 4,
        location: [55.642063, 37.656123],
        type: "shop",
        title: "Магазины",
        infoLeft: "Reserved, Cropp, Zara",
      },
      {
        id: 5,
        location: [55.642063, 37.656123],
        type: "food",
        title: "Семейный ресторан",
        infoLeft: "Своя компания",
        infoRight: "₽₽",
      },
      {
        id: 6,
        location: [55.642063, 37.656123],
        type: "sport",
        title: "Спортзал",
      },
      {
        id: 7,
        location: [55.642063, 37.656123],
        type: "transport",
        title: "Метро",
        infoLeft: "Остановка 'Достоевская'",
      },
      {
        id: 8,
        location: [55.642063, 37.656123],
        type: "kindergarten",
        title: "Детский сад",
        infoLeft: "400 мест",
        infoRight: "Сдан",
      },
    ],
    district: "Стоический",
    openDate: "2022-04-11T15:00:00.000+05:00",
    image: { image: "image18.png", imageSmall: "image18small.png" },
    images: [
      { image: "image18.png", imageSmall: "image18small.png" },
      { image: "image18.png", imageSmall: "image18small.png" },
      { image: "image18.png", imageSmall: "image18small.png" },
    ],
    genLayout: "svg1.svg",
    buildings: [ buildings[0], buildings[1], buildings[2] ],
    newShapes: true,
    flats: [
      {
        id: 2,
        name: "1-комн.",
        type: 1,
        price: 4000000,
        amount: 3,
      },
      {
        id: 4,
        name: "2-комн.",
        type: 2,
        price: 3000000,
        amount: 1,
      },
      {
        id: 5,
        name: "3-комн.",
        type: 3,
        price: 3500000,
        amount: 12,
      },
    ],
  },
  {
    id: 15,
    name: "Плюс один",
    address: "Ижевск, ул. Великая",
    type: "ЖК",
    minPrice: 3500000,
    space: 131,
    about: {
      text: [
        `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
        `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
      ],
      images: [
        { image: "image27.jpg", imageSmall: "image27small.jpg" },
        { image: "image26.jpg", imageSmall: "image26small.jpg" },
        { image: "image27.jpg", imageSmall: "image27small.jpg" },
      ],
    },
    location: [55.826179, 37.487708],
    nearerObjects: [
      {
        id: 1,
        location: [55.826479, 37.487208],
        type: "culture",
        title: "Театр",
        infoLeft: "1060 мест",
        infoRight: "с 1960г",
      },
      {
        id: 2,
        location: [55.826479, 37.487208],
        type: "medicine",
        title: "поликлиника",
        infoLeft: "Лотос",
      },
      {
        id: 3,
        location: [55.826479, 37.487208],
        type: "education",
        title: "Школа",
        infoLeft: "1060 мест",
        infoRight: "Сдан",
      },
      {
        id: 4,
        location: [55.826479, 37.487208],
        type: "shop",
        title: "Магазины",
        infoLeft: "Reserved, Cropp, Zara",
      },
      {
        id: 5,
        location: [55.826479, 37.487208],
        type: "food",
        title: "Семейный ресторан",
        infoLeft: "Своя компания",
        infoRight: "₽₽",
      },
      {
        id: 6,
        location: [55.826479, 37.487208],
        type: "sport",
        title: "Спортзал",
      },
      {
        id: 7,
        location: [55.826479, 37.487208],
        type: "transport",
        title: "Метро",
        infoLeft: "Остановка 'Достоевская'",
      },
      {
        id: 8,
        location: [55.826479, 37.487208],
        type: "kindergarten",
        title: "Детский сад",
        infoLeft: "400 мест",
        infoRight: "Сдан",
      },
    ],
    district: "Стоический",
    openDate: "2025-12-12T15:00:00.000+05:00",
    image: { image: "image19.png", imageSmall: "image19small.png" },
    images: [
      { image: "image19.png", imageSmall: "image19small.png" },
      { image: "image19.png", imageSmall: "image19small.png" },
      { image: "image19.png", imageSmall: "image19small.png" },
    ],
    genLayout: "svg1.svg",
    buildings: [ buildings[0], buildings[1], buildings[2] ],
    newShapes: true,
    flats: [
      {
        id: 2,
        name: "1-комн.",
        type: 1,
        price: 4000000,
        amount: 3,
      },
      {
        id: 4,
        name: "2-комн.",
        type: 2,
        price: 3000000,
        amount: 1,
      },
      {
        id: 5,
        name: "3-комн.",
        type: 3,
        price: 3500000,
        amount: 12,
      },
    ],
  },
];

export const Offices = [
  {
    id: 1,
    name: "Forest",
    minPrice: 6500000,
    space: 134,
    roomsAmount: 5,
    address: "Ижевск, ул. Союзная",
    type: "ЖК",
    about: {
      text: [
        `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
        `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
      ],
      images: ["image27.jpg", "image26.jpg", "image27.jpg"],
    },
    location: [55.684758, 37.738521],
    nearerObjects: [
      {
        id: 1,
        location: [55.684758, 37.738521],
        type: "culture",
        title: "Театр",
        infoLeft: "1060 мест",
        infoRight: "с 1960г",
      },
      {
        id: 2,
        location: [55.684758, 37.738521],
        type: "medicine",
        title: "поликлиника",
        infoLeft: "Лотос",
      },
      {
        id: 3,
        location: [55.684758, 37.738521],
        type: "education",
        title: "Школа",
        infoLeft: "1060 мест",
        infoRight: "Сдан",
      },
      {
        id: 4,
        location: [55.684758, 37.738521],
        type: "shop",
        title: "Магазины",
        infoLeft: "Reserved, Cropp, Zara",
      },
      {
        id: 5,
        location: [55.684758, 37.738521],
        type: "food",
        title: "Семейный ресторан",
        infoLeft: "Своя компания",
        infoRight: "₽₽",
      },
      {
        id: 6,
        location: [55.684758, 37.738521],
        type: "sport",
        title: "Спортзал",
      },
      {
        id: 7,
        location: [55.684758, 37.738521],
        type: "transport",
        title: "Метро",
        infoLeft: "Остановка 'Достоевская'",
      },
      {
        id: 8,
        location: [55.684758, 37.738521],
        type: "kindergarten",
        title: "Детский сад",
        infoLeft: "400 мест",
        infoRight: "Сдан",
      },
    ],
    district: "Ульяновский",
    openDate: "2017-05-15T08:30:00.000+05:00",
    image: "image13.png",
    images: ["image13.png", "image13.png", "image13.png"],
    genLayout: "svg1.svg",
    buildings: [ buildings[0], buildings[1], buildings[2] ],
    discount: "10%",
    newShapes: true,
  },
  {
    id: 2,
    name: "Forest",
    minPrice: 6500000,
    space: 130,
    roomsAmount: 3,
    address: "Ижевск, ул. Союзная",
    type: "ЖК",
    about: {
      text: [
        `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
        `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
      ],
      images: ["image27.jpg", "image26.jpg", "image27.jpg"],
    },
    location: [55.833436, 37.715175],
    nearerObjects: [
      {
        id: 1,
        location: [55.833436, 37.715175],
        type: "culture",
        title: "Театр",
        infoLeft: "1060 мест",
        infoRight: "с 1960г",
      },
      {
        id: 2,
        location: [55.833436, 37.715175],
        type: "medicine",
        title: "поликлиника",
        infoLeft: "Лотос",
      },
      {
        id: 3,
        location: [55.833436, 37.715175],
        type: "education",
        title: "Школа",
        infoLeft: "1060 мест",
        infoRight: "Сдан",
      },
      {
        id: 4,
        location: [55.833436, 37.715175],
        type: "shop",
        title: "Магазины",
        infoLeft: "Reserved, Cropp, Zara",
      },
      {
        id: 5,
        location: [55.833436, 37.715175],
        type: "food",
        title: "Семейный ресторан",
        infoLeft: "Своя компания",
        infoRight: "₽₽",
      },
      {
        id: 6,
        location: [55.833436, 37.715175],
        type: "sport",
        title: "Спортзал",
      },
      {
        id: 7,
        location: [55.833436, 37.715175],
        type: "transport",
        title: "Метро",
        infoLeft: "Остановка 'Достоевская'",
      },
      {
        id: 8,
        location: [55.833436, 37.715175],
        type: "kindergarten",
        title: "Детский сад",
        infoLeft: "400 мест",
        infoRight: "Сдан",
      },
    ],
    district: "Ульяновский",
    openDate: "2028-08-10T12:00:00.000+05:00",
    image: "image16.png",
    images: ["image16.png", "image16.png", "image16.png"],
    genLayout: "svg1.svg",
    buildings: [ buildings[0], buildings[1], buildings[2] ],
    discount: "50%",
    newShapes: true,
  },
  {
    id: 3,
    name: "Плюс один",
    minPrice: 4500000,
    space: 80,
    roomsAmount: 3,
    address: "Ижевск, ул. Союзная",
    type: "ЖК",
    about: {
      text: [
        `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
        `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
      ],
      images: ["image27.jpg", "image26.jpg", "image27.jpg"],
    },
    location: [55.687086, 37.529789],
    nearerObjects: [
      {
        id: 1,
        location: [55.687086, 37.529789],
        type: "culture",
        title: "Театр",
        infoLeft: "1060 мест",
        infoRight: "с 1960г",
      },
      {
        id: 2,
        location: [55.687086, 37.529789],
        type: "medicine",
        title: "поликлиника",
        infoLeft: "Лотос",
      },
      {
        id: 3,
        location: [55.687086, 37.529789],
        type: "education",
        title: "Школа",
        infoLeft: "1060 мест",
        infoRight: "Сдан",
      },
      {
        id: 4,
        location: [55.687086, 37.529789],
        type: "shop",
        title: "Магазины",
        infoLeft: "Reserved, Cropp, Zara",
      },
      {
        id: 5,
        location: [55.687086, 37.529789],
        type: "food",
        title: "Семейный ресторан",
        infoLeft: "Своя компания",
        infoRight: "₽₽",
      },
      {
        id: 6,
        location: [55.687086, 37.529789],
        type: "sport",
        title: "Спортзал",
      },
      {
        id: 7,
        location: [55.687086, 37.529789],
        type: "transport",
        title: "Метро",
        infoLeft: "Остановка 'Достоевская'",
      },
      {
        id: 8,
        location: [55.687086, 37.529789],
        type: "kindergarten",
        title: "Детский сад",
        infoLeft: "400 мест",
        infoRight: "Сдан",
      },
    ],
    district: "Ульяновский",
    openDate: "2021-02-20T15:00:00.000+05:00",
    image: "image17.png",
    images: ["image17.png", "image17.png", "image17.png"],
    genLayout: "svg1.svg",
    buildings: [ buildings[0], buildings[1], buildings[2] ],
    newShapes: true,
  },
  {
    id: 4,
    name: "Васнецово",
    minPrice: 5500000,
    space: 120,
    roomsAmount: 6,
    address: "Ижевск, ул. Танкограда",
    type: "ЖК",
    about: {
      text: [
        `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
        `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
      ],
      images: ["image27.jpg", "image26.jpg", "image27.jpg"],
    },
    location: [55.782392, 37.611724],
    nearerObjects: [
      {
        id: 1,
        location: [55.782602, 37.614034],
        type: "culture",
        title: "Театр",
        infoLeft: "1060 мест",
        infoRight: "с 1960г",
      },
      {
        id: 2,
        location: [55.782192, 37.611524],
        type: "medicine",
        title: "поликлиника",
        infoLeft: "Лотос",
      },
      {
        id: 3,
        location: [55.782182, 37.611834],
        type: "education",
        title: "Школа",
        infoLeft: "1060 мест",
        infoRight: "Сдан",
      },
      {
        id: 4,
        location: [55.782082, 37.611934],
        type: "shop",
        title: "Магазины",
        infoLeft: "Reserved, Cropp, Zara",
      },
      {
        id: 5,
        location: [55.782882, 37.610834],
        type: "food",
        title: "Семейный ресторан",
        infoLeft: "Своя компания",
        infoRight: "₽₽",
      },
      {
        id: 6,
        location: [55.782582, 37.612834],
        type: "sport",
        title: "Спортзал",
      },
      {
        id: 7,
        location: [55.782452, 37.612634],
        type: "transport",
        title: "Метро",
        infoLeft: "Остановка 'Достоевская'",
      },
      {
        id: 8,
        location: [55.7823, 37.611934],
        type: "kindergarten",
        title: "Детский сад",
        infoLeft: "400 мест",
        infoRight: "Сдан",
      },
    ],
    district: "Пчкаловский",
    openDate: "2021-10-03T15:00:00.000+05:00",
    image: "image27.jpg",
    images: ["image27.jpg", "image26.jpg", "image27.jpg"],
    genLayout: "svg1.svg",
    buildings: [ buildings[0], buildings[1], buildings[2] ],
    discount: "10%",
    newShapes: true,
  },
  {
    id: 5,
    name: "ARTNOVA",
    minPrice: 7500000,
    space: 145,
    roomsAmount: 1,
    address: "Ижевск, ул. Великая",
    type: "ЖК",
    about: {
      text: [
        `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
        `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
      ],
      images: ["image27.jpg", "image26.jpg", "image27.jpg"],
    },
    location: [55.642063, 37.656123],
    nearerObjects: [
      {
        id: 1,
        location: [55.642063, 37.656123],
        type: "culture",
        title: "Театр",
        infoLeft: "1060 мест",
        infoRight: "с 1960г",
      },
      {
        id: 2,
        location: [55.642063, 37.656123],
        type: "medicine",
        title: "поликлиника",
        infoLeft: "Лотос",
      },
      {
        id: 3,
        location: [55.642063, 37.656123],
        type: "education",
        title: "Школа",
        infoLeft: "1060 мест",
        infoRight: "Сдан",
      },
      {
        id: 4,
        location: [55.642063, 37.656123],
        type: "shop",
        title: "Магазины",
        infoLeft: "Reserved, Cropp, Zara",
      },
      {
        id: 5,
        location: [55.642063, 37.656123],
        type: "food",
        title: "Семейный ресторан",
        infoLeft: "Своя компания",
        infoRight: "₽₽",
      },
      {
        id: 6,
        location: [55.642063, 37.656123],
        type: "sport",
        title: "Спортзал",
      },
      {
        id: 7,
        location: [55.642063, 37.656123],
        type: "transport",
        title: "Метро",
        infoLeft: "Остановка 'Достоевская'",
      },
      {
        id: 8,
        location: [55.642063, 37.656123],
        type: "kindergarten",
        title: "Детский сад",
        infoLeft: "400 мест",
        infoRight: "Сдан",
      },
    ],
    district: "Стоический",
    openDate: "2022-04-11T15:00:00.000+05:00",
    image: "image18.png",
    images: ["image18.png", "image18.png", "image18.png"],
    genLayout: "svg1.svg",
    buildings: [ buildings[0], buildings[1], buildings[2] ],
    newShapes: true,
  },
  {
    id: 6,
    name: "Плюс один",
    minPrice: 4000000,
    space: 78,
    roomsAmount: 4,
    address: "Ижевск, ул. Великая",
    type: "ЖК",
    about: {
      text: [
        `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
        `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
      ],
      images: ["image27.jpg", "image26.jpg", "image27.jpg"],
    },
    location: [55.826479, 37.487208],
    nearerObjects: [
      {
        id: 1,
        location: [55.826479, 37.487208],
        type: "culture",
        title: "Театр",
        infoLeft: "1060 мест",
        infoRight: "с 1960г",
      },
      {
        id: 2,
        location: [55.826479, 37.487208],
        type: "medicine",
        title: "поликлиника",
        infoLeft: "Лотос",
      },
      {
        id: 3,
        location: [55.826479, 37.487208],
        type: "education",
        title: "Школа",
        infoLeft: "1060 мест",
        infoRight: "Сдан",
      },
      {
        id: 4,
        location: [55.826479, 37.487208],
        type: "shop",
        title: "Магазины",
        infoLeft: "Reserved, Cropp, Zara",
      },
      {
        id: 5,
        location: [55.826479, 37.487208],
        type: "food",
        title: "Семейный ресторан",
        infoLeft: "Своя компания",
        infoRight: "₽₽",
      },
      {
        id: 6,
        location: [55.826479, 37.487208],
        type: "sport",
        title: "Спортзал",
      },
      {
        id: 7,
        location: [55.826479, 37.487208],
        type: "transport",
        title: "Метро",
        infoLeft: "Остановка 'Достоевская'",
      },
      {
        id: 8,
        location: [55.826479, 37.487208],
        type: "kindergarten",
        title: "Детский сад",
        infoLeft: "400 мест",
        infoRight: "Сдан",
      },
    ],
    district: "Стоический",
    openDate: "2025-12-12T15:00:00.000+05:00",
    image: "image19.png",
    images: ["image19.png", "image19.png", "image19.png"],
    genLayout: "svg1.svg",
    buildings: [ buildings[0], buildings[1], buildings[2] ],
    newShapes: true,
  },
];
