export const newsCards = [
  {
    id: 1,
    title:
      "Лес начинается с тебя новые экологичные проекты для комфортной жизни",
    desc: "Темп глобализации постоянно растет, и большая часть украинских девелоперов теперь ничем не отличается от застройщиков из Китая, США",
    date: "9 октября 2021",
  },
  {
    id: 2,
    title: "17 лет только начало",
    desc: "Темп глобализации постоянно растет, и большая часть украинских девелоперов теперь ничем не отличается от застройщиков из Китая, США",
    date: "9 октября 2021",
  },
  {
    id: 3,
    title: "Лес начинается с тебя новые экологичные проекты",
    desc: "Темп глобализации постоянно растет, и большая часть украинских девелоперов теперь ничем не отличается от застройщиков из Китая, США",
    date: "9 октября 2021",
  },
  {
    id: 4,
    title:
      "Лес начинается с тебя новые экологичные проекты для комфортной жизни",
    desc: "Темп глобализации постоянно растет, и большая часть украинских девелоперов теперь ничем не отличается от застройщиков из Китая, США",
    date: "9 октября 2021",
  },
  {
    id: 5,
    title: "17 лет только начало",
    desc: "Темп глобализации постоянно растет, и большая часть украинских девелоперов теперь ничем не отличается от застройщиков из Китая, США",
    date: "9 октября 2021",
  },
  {
    id: 6,
    title: "Лес начинается с тебя новые экологичные проекты",
    desc: "Темп глобализации постоянно растет, и большая часть украинских девелоперов теперь ничем не отличается от застройщиков из Китая, США",
    date: "9 октября 2021",
  },
  {
    id: 7,
    title:
      "Лес начинается с тебя новые экологичные проекты для комфортной жизни",
    desc: "Темп глобализации постоянно растет, и большая часть украинских девелоперов теперь ничем не отличается от застройщиков из Китая, США",
    date: "9 октября 2021",
  },
  {
    id: 8,
    title: "17 лет только начало",
    desc: "Темп глобализации постоянно растет, и большая часть украинских девелоперов теперь ничем не отличается от застройщиков из Китая, США",
    date: "9 октября 2021",
  },
  {
    id: 9,
    title: "Лес начинается с тебя новые экологичные проекты",
    desc: "Темп глобализации постоянно растет, и большая часть украинских девелоперов теперь ничем не отличается от застройщиков из Китая, США",
    date: "9 октября 2021",
  },
  {
    id: 10,
    title:
      "Лес начинается с тебя новые экологичные проекты для комфортной жизни",
    desc: "Темп глобализации постоянно растет, и большая часть украинских девелоперов теперь ничем не отличается от застройщиков из Китая, США",
    date: "9 октября 2021",
  },
  {
    id: 11,
    title: "17 лет только начало",
    desc: "Темп глобализации постоянно растет, и большая часть украинских девелоперов теперь ничем не отличается от застройщиков из Китая, США",
    date: "9 октября 2021",
  },
  {
    id: 12,
    title: "Лес начинается с тебя новые экологичные проекты",
    desc: "Темп глобализации постоянно растет, и большая часть украинских девелоперов теперь ничем не отличается от застройщиков из Китая, США",
    date: "9 октября 2021",
  },
];

export const houseCards = [
  {
    id: 1,
    name: "Forest",
    adress: "Ижевск, ул. Союзная",
    type: "ЖК",
    district: "Ульяновский",
    location: [55.684758, 37.738521],
    price: 3500000,
    space: 70,
    openDate: "2017-05-15T08:30:00.000+05:00",
    image: { image: "image13.png", smallimage: "image13small.png" },
    images: [
      { image: "image13.png", smallimage: "image13small.png" },
      { image: "image13.png", smallimage: "image13small.png" },
      { image: "image13.png", smallimage: "image13small.png" },
    ],
    buildings: [
      {
        id: 1,
        number: "3",
        datePic: "2017-05-15T08:30:00.000+05:00",
        images: ["image24.png", "image25.png", "image26.png"],
      },
      {
        id: 2,
        number: "2",
        datePic: "2017-05-15T08:30:00.000+05:00",
        images: ["image25.png", "image24.png", "image26.png"],
      },
    ],
    discount: "10%",
    newShapes: true,
    flats: [
      {
        id: 2,
        name: "1-комн.",
        type: 1,
        price: 4000000,
        layouts: ["image22.png", "image22.png"],
        house: 2,
        space: 16.4,
        amount: 3,
      },
      {
        id: 4,
        name: "2-комн.",
        type: 2,
        price: 3000000,
        layouts: ["image23.png", "image22.png"],
        house: 2,
        space: 21.4,
        amount: 1,
      },
      {
        id: 5,
        name: "3-комн.",
        type: 3,
        price: 3500000,
        layouts: ["image23.png", "image22.png"],
        house: 2,
        space: 25.4,
        amount: 12,
      },
    ],
  },
  {
    id: 2,
    name: "Forest",
    adress: "Ижевск, ул. Союзная",
    type: "ЖК",
    location: [55.833436, 37.715175],
    district: "Ульяновский",
    price: 4500000,
    space: 24,
    openDate: "2028-08-10T12:00:00.000+05:00",
    image: "image16.png",
    images: ["image16.png", "image16.png", "image16.png"],
    buildings: [
      {
        id: 1,
        number: "3",
        datePic: "2028-08-10T12:00:00.000+05:00",
        images: ["image24.png", "image25.png", "image26.png"],
      },
      {
        id: 2,
        number: "2",
        datePic: "2028-08-10T12:00:00.000+05:00",
        images: ["image25.png", "image24.png", "image26.png"],
      },
    ],
    discount: "50%",
    newShapes: true,
    flats: [
      {
        id: 2,
        name: "1-комн.",
        type: 1,
        price: 4000000,
        layouts: ["image22.png", "image22.png"],
        house: 2,
        space: 16.4,
        amount: 3,
      },
    ],
  },
  {
    id: 3,
    name: "Плюс один",
    adress: "Ижевск, ул. Союзная",
    type: "ЖК",
    location: [55.687086, 37.529789],
    district: "Ульяновский",
    price: 6500000,
    space: 224,
    openDate: "2021-02-20T15:00:00.000+05:00",
    image: "image17.png",
    images: ["image17.png", "image17.png", "image17.png"],
    buildings: [
      {
        id: 1,
        number: "3",
        datePic: "2021-02-20T15:00:00.000+05:00",
        images: ["image24.png", "image25.png", "image26.png"],
      },
      {
        id: 2,
        number: "2",
        datePic: "2021-02-20T15:00:00.000+05:00",
        images: ["image25.png", "image24.png", "image26.png"],
      },
    ],
    newShapes: true,
    flats: [
      {
        id: 1,
        name: "Студия",
        type: 0,
        price: 4500000,
        layouts: ["image21.png", "image22.png"],
        house: 2,
        space: 21.4,
        amount: 2,
      },
      {
        id: 2,
        name: "1-комн.",
        type: 1,
        price: 4000000,
        layouts: ["image22.png", "image22.png"],
        house: 2,
        space: 16.4,
        amount: 3,
      },
    ],
  },
  {
    id: 4,
    name: "Васнецово",
    adress: "Ижевск, ул. Танкограда",
    type: "ЖК",
    levels: [
      {
        level: 1,
        flats: [
          {
            id: 111,
            flat: 1,
            number: 7,
            price: 4500000,
            styles: { width: "16%", height: "34%", left: "24%", top: "9%" },
          },
          { flat: 2, clipPath: [] },
          3,
          4,
          5,
          6,
        ],
        image: "image27.png",
      },
      {
        level: 2,
        flats: [
          {
            id: 121,
            flat: 1,
            number: 7,
            price: 4500000,
            styles: { width: "16%", height: "34%", left: "24%", top: "9%" },
          },
          { flat: 2, clipPath: [] },
          3,
          4,
          5,
          6,
        ],
        image: "image27.png",
      },
      {
        level: 3,
        flats: [
          {
            id: 131,
            flat: 1,
            number: 7,
            price: 4500000,
            styles: { width: "16%", height: "34%", left: "24%", top: "9%" },
          },
          { flat: 2, clipPath: [] },
          3,
          4,
          5,
          6,
        ],
        image: "image27.png",
      },
      {
        level: 4,
        flats: [
          {
            id: 131,
            flat: 1,
            number: 7,
            price: 4500000,
            styles: { width: "16%", height: "34%", left: "24%", top: "9%" },
          },
          { flat: 2, clipPath: [] },
          3,
          4,
          5,
          6,
        ],
        image: "image27.png",
      },
      {
        level: 5,
        flats: [
          {
            id: 131,
            flat: 1,
            number: 7,
            price: 4500000,
            styles: { width: "16%", height: "34%", left: "24%", top: "9%" },
          },
          { flat: 2, clipPath: [] },
          3,
          4,
          5,
          6,
        ],
        image: "image27.png",
      },
      {
        level: 6,
        flats: [
          {
            id: 131,
            flat: 1,
            number: 7,
            price: 4500000,
            styles: { width: "16%", height: "34%", left: "24%", top: "9%" },
          },
          { flat: 2, clipPath: [] },
          3,
          4,
          5,
          6,
        ],
        image: "image27.png",
      },
      {
        level: 7,
        flats: [
          {
            id: 131,
            flat: 1,
            number: 7,
            price: 4500000,
            styles: { width: "16%", height: "34%", left: "24%", top: "9%" },
          },
          { flat: 2, clipPath: [] },
          3,
          4,
          5,
          6,
        ],
        image: "image27.png",
      },
      {
        level: 8,
        flats: [
          {
            id: 131,
            flat: 1,
            number: 7,
            price: 4500000,
            styles: { width: "16%", height: "34%", left: "24%", top: "9%" },
          },
          { flat: 2, clipPath: [] },
          3,
          4,
          5,
          6,
        ],
        image: "image27.png",
      },
      {
        level: 9,
        flats: [
          {
            id: 131,
            flat: 1,
            number: 7,
            price: 4500000,
            styles: { width: "16%", height: "34%", left: "24%", top: "9%" },
          },
          { flat: 2, clipPath: [] },
          3,
          4,
          5,
          6,
        ],
        image: "image27.png",
      },
      {
        level: 10,
        flats: [
          {
            id: 131,
            flat: 1,
            number: 7,
            price: 4500000,
            styles: { width: "16%", height: "34%", left: "24%", top: "9%" },
          },
          { flat: 2, clipPath: [] },
          3,
          4,
          5,
          6,
        ],
        image: "image27.png",
      },
      {
        level: 11,
        flats: [
          {
            id: 131,
            flat: 1,
            number: 7,
            price: 4500000,
            styles: { width: "16%", height: "34%", left: "24%", top: "9%" },
          },
          { flat: 2, clipPath: [] },
          3,
          4,
          5,
          6,
        ],
        image: "image27.png",
      },
      {
        level: 12,
        flats: [
          {
            id: 131,
            flat: 1,
            number: 7,
            price: 4500000,
            styles: { width: "16%", height: "34%", left: "24%", top: "9%" },
          },
          { flat: 2, clipPath: [] },
          3,
          4,
          5,
          6,
        ],
        image: "image27.png",
      },
      {
        level: 13,
        flats: [
          {
            id: 131,
            flat: 1,
            number: 7,
            price: 4500000,
            styles: { width: "16%", height: "34%", left: "24%", top: "9%" },
          },
          { flat: 2, clipPath: [] },
          3,
          4,
          5,
          6,
        ],
        image: "image27.png",
      },
      {
        level: 14,
        flats: [
          {
            id: 131,
            flat: 1,
            number: 7,
            price: 4500000,
            styles: { width: "16%", height: "34%", left: "24%", top: "9%" },
          },
          { flat: 2, clipPath: [] },
          3,
          4,
          5,
          6,
        ],
        image: "image27.png",
      },
      {
        level: 15,
        flats: [
          {
            id: 131,
            flat: 1,
            number: 7,
            price: 4500000,
            styles: { width: "16%", height: "34%", left: "24%", top: "9%" },
          },
          { flat: 2, clipPath: [] },
          3,
          4,
          5,
          6,
        ],
        image: "image27.png",
      },
      {
        level: 16,
        flats: [
          {
            id: 131,
            flat: 1,
            number: 7,
            price: 4500000,
            styles: { width: "16%", height: "34%", left: "24%", top: "9%" },
          },
          { flat: 2, clipPath: [] },
          3,
          4,
          5,
          6,
        ],
        image: "image27.png",
      },
      {
        level: 17,
        flats: [
          {
            id: 131,
            flat: 1,
            number: 7,
            price: 4500000,
            styles: { width: "16%", height: "34%", left: "24%", top: "9%" },
          },
          { flat: 2, clipPath: [] },
          3,
          4,
          5,
          6,
        ],
        image: "image27.png",
      },
      {
        level: 18,
        flats: [
          {
            id: 131,
            flat: 1,
            number: 7,
            price: 4500000,
            styles: { width: "16%", height: "34%", left: "24%", top: "9%" },
          },
          { flat: 2, clipPath: [] },
          3,
          4,
          5,
          6,
        ],
        image: "image27.png",
      },
      {
        level: 19,
        flats: [
          {
            id: 131,
            flat: 1,
            number: 7,
            price: 4500000,
            styles: { width: "16%", height: "34%", left: "24%", top: "9%" },
          },
          { flat: 2, clipPath: [] },
          3,
          4,
          5,
          6,
        ],
        image: "image27.png",
      },
      {
        level: 20,
        flats: [
          {
            id: 131,
            flat: 1,
            number: 7,
            price: 4500000,
            styles: { width: "16%", height: "34%", left: "24%", top: "9%" },
          },
          { flat: 2, clipPath: [] },
          3,
          4,
          5,
          6,
        ],
        image: "image27.png",
      },
    ],
    about: {
      text: [
        `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
        `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
      ],
      images: ["image27.jpg", "image26.jpg", "image27.jpg"],
    },
    location: [55.782392, 37.611724],
    nearerObjects: [
      {
        id: 1,
        location: [55.782602, 37.614034],
        type: "culture",
        title: "Театр",
        infoLeft: "1060 мест",
        infoRight: "с 1960г",
      },
      {
        id: 2,
        location: [55.782192, 37.611524],
        type: "medecine",
        title: "поликлиника",
        infoLeft: "Лотос",
      },
      {
        id: 3,
        location: [55.782182, 37.611834],
        type: "education",
        title: "Школа",
        infoLeft: "1060 мест",
        infoRight: "Сдан",
      },
      {
        id: 4,
        location: [55.782082, 37.611934],
        type: "shop",
        title: "Магазины",
        infoLeft: "Reserved, Cropp, Zara",
      },
      {
        id: 5,
        location: [55.782882, 37.610834],
        type: "food",
        title: "Семейный ресторан",
        infoLeft: "Своя компания",
        infoRight: "₽₽",
      },
      {
        id: 6,
        location: [55.782582, 37.612834],
        type: "sport",
        title: "Спортзал",
      },
      {
        id: 7,
        location: [55.782452, 37.612634],
        type: "transport",
        title: "Метро",
        infoLeft: "Остановка 'Достоевская'",
      },
      {
        id: 8,
        location: [55.7823, 37.611934],
        type: "kindergarden",
        title: "Детский сад",
        infoLeft: "400 мест",
        infoRight: "Сдан",
      },
    ],
    district: "Пчкаловский",
    price: 3000000,
    space: 124,
    openDate: "2021-10-03T15:00:00.000+05:00",
    image: "image27.jpg",
    images: ["image27.jpg", "image26.jpg", "image27.jpg"],
    genlayout: "svg1.svg",
    parking: {
      image: "image28.png",
      slots: [
        {
          price: 86000,
          number: 11,
          styles: {
            clipPath: ``,
            width: "5%",
            height: "13.5%",
            left: "13%",
            top: "4%",
          },
        },
        {
          price: 86000,
          number: 10,
          styles: {
            clipPath: ``,
            width: "5%",
            height: "13.5%",
            left: "17.7%",
            top: "4%",
          },
        },
        {
          price: 86000,
          number: 19,
          styles: {
            clipPath: ``,
            width: "5%",
            height: "15%",
            left: "35.7%",
            top: "36.6%",
          },
        },
        {
          price: 86000,
          number: 18,
          styles: {
            clipPath: ``,
            width: "5%",
            height: "15%",
            left: "40.8%",
            top: "36.6%",
          },
        },
        {
          price: 86000,
          number: 14,
          styles: {
            clipPath: ``,
            width: "5%",
            height: "15%",
            left: "65.3%",
            top: "36.6%",
          },
        },
        {
          price: 86000,
          number: 32,
          styles: {
            clipPath: ``,
            width: "5%",
            height: "14%",
            top: "85.9%",
            left: "70.8%",
          },
        },
      ],
    },
    larder: {
      image: "image27.png",
      slots: [
        {
          price: 86000,
          number: 11,
          styles: {
            clipPath: ``,
            width: "22.1%",
            height: "32.5%",
            top: "10%",
            left: "1.5%",
          },
        },
        {
          price: 86000,
          number: 10,
          styles: {
            clipPath: ``,
            width: "16%",
            height: "33.5%",
            left: "60%",
            top: "54%",
          },
        },
      ],
    },
    buildings: [
      {
        id: 1,
        number: "3",
        datePic: "2021-10-03T15:00:00.000+05:00",
        images: [
          { image: "image24.png", smallimage: "image24small.png" },
          { image: "image25.png", smallimage: "image25small.png" },
          { image: "image26.png", smallimage: "image26small.png" },
        ],
        styles: {
          clipPath: `polygon(9px 66px, 27px 47px, 2px 24px, 16px 8px, 45px 29px, 73px 1px, 89px 16px, 25px 82px)`,
          width: "31.5%",
          height: "29.5%",
          left: "65%",
          top: "68%",
        },
      },
      {
        id: 2,
        number: "2",
        datePic: "2021-12-03T15:00:00.000+05:00",
        images: [
          { image: "image25.png", smallimage: "image25small.png" },
          { image: "image24.png", smallimage: "image24small.png" },
          { image: "image26.png", smallimage: "image26small.png" },
        ],
        styles: {
          clipPath: `polygon(9px 66px, 27px 47px, 2px 24px, 16px 8px, 45px 29px, 73px 1px, 89px 16px, 25px 82px)`,
          width: "31.5%",
          height: "29.5%",
          left: "65%",
          top: "68%",
        },
      },
      {
        id: 3,
        number: "4",
        datePic: "2021-12-03T15:00:00.000+05:00",
        images: [
          { image: "image26.png", smallimage: "image26small.png" },
          { image: "image24.png", smallimage: "image24small.png" },
          { image: "image25.png", smallimage: "image25small.png" },
        ],
      },
    ],
    discount: "10%",
    newShapes: true,
    flats: [
      {
        id: 1,
        name: "Студия",
        flatNumber: 12,
        entrance: 5,
        street: "10 лет Октября",
        district: "Пчкаловский",
        type: 0,
        price: 4500000,
        finishingPrice: 477000,
        layouts: ["image21.png", "image22.png"],
        house: "2",
        space: 21.4,
        degree: 120,
        amount: 2,
        openDate: "2021-10-03T15:00:00.000+05:00",
        about: {
          title: "Отделка",
          text: [
            `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
            `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
          ],
          images: ["image28.jpg", "image29.jpg", "image28.jpg"],
        },
        options: [
          { title: "Кладовку", image: "image31.jpg" },
          { title: "Парковку", image: "image30.jpg" },
        ],
      },
      {
        id: 2,
        name: "1-комн.",
        flatNumber: 12,
        entrance: 5,
        street: "10 лет Октября",
        district: "Пчкаловский",
        type: 1,
        price: 4000000,
        finishingPrice: 477000,
        layouts: ["image22.png", "image22.png"],
        house: "2",
        space: 16.4,
        degree: 140,
        amount: 3,
        openDate: "2021-10-03T15:00:00.000+05:00",
        about: {
          title: "Отделка",
          text: [
            `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
            `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
          ],
          images: ["image29.jpg", "image28.jpg", "image29.jpg"],
        },
        options: [
          { title: "Кладовку", image: "image31.jpg" },
          { title: "Парковку", image: "image30.jpg" },
        ],
      },
      {
        id: 4,
        name: "2-комн.",
        flatNumber: 12,
        entrance: 5,
        street: "10 лет Октября",
        district: "Пчкаловский",
        type: 2,
        price: 3000000,
        finishingPrice: 477000,
        layouts: ["image23.png", "image22.png"],
        house: "2",
        space: 21.4,
        degree: 0,
        amount: 1,
        openDate: "2021-10-03T15:00:00.000+05:00",
        about: {
          title: "Отделка",
          text: [
            `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
            `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
          ],
          images: ["image28.jpg", "image29.jpg", "image28.jpg"],
        },
        options: [
          { title: "Кладовку", image: "image31.jpg" },
          { title: "Парковку", image: "image30.jpg" },
        ],
      },
      {
        id: 5,
        name: "3-комн.",
        flatNumber: 12,
        entrance: 5,
        street: "10 лет Октября",
        district: "Пчкаловский",
        type: 3,
        price: 3500000,
        finishingPrice: 477000,
        layouts: ["image23.png", "image22.png"],
        house: "2",
        space: 25.4,
        degree: 70,
        amount: 12,
        openDate: "2021-10-03T15:00:00.000+05:00",
        about: {
          title: "Отделка",
          text: [
            `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
            `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
          ],
          images: ["image29.jpg", "image28.jpg", "image29.jpg"],
        },
        options: [
          { title: "Кладовку", image: "image31.jpg" },
          { title: "Парковку", image: "image30.jpg" },
        ],
      },
      {
        id: 6,
        name: "4-комн.",
        flatNumber: 12,
        entrance: 5,
        street: "10 лет Октября",
        district: "Пчкаловский",
        type: 4,
        price: 3500000,
        finishingPrice: 477000,
        layouts: ["image23.png", "image22.png"],
        house: "2",
        space: 36.4,
        degree: 40,
        amount: 12,
        openDate: "2021-10-03T15:00:00.000+05:00",
        about: {
          title: "Отделка",
          text: [
            `Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`,
            `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`,
          ],
          images: ["image28.jpg", "image29.jpg", "image28.jpg"],
        },
        options: [
          { title: "Кладовку", image: "image31.jpg" },
          { title: "Парковку", image: "image30.jpg" },
        ],
      },
    ],
  },
  {
    id: 5,
    name: "ARTNOVA",
    adress: "Ижевск, ул. Великая",
    type: "ЖК",
    location: [55.642063, 37.656123],
    district: "Стоический",
    price: 6500000,
    space: 14,
    openDate: "2022-04-11T15:00:00.000+05:00",
    image: "image18.png",
    images: ["image18.png", "image18.png", "image18.png"],
    buildings: [
      {
        id: 1,
        number: "3",
        datePic: "2022-04-11T15:00:00.000+05:00",
        images: ["image13.png", "image13.png", "image13.png"],
      },
      {
        id: 2,
        number: "2",
        datePic: "2022-04-11T15:00:00.000+05:00",
        images: ["image13.png", "image13.png", "image13.png"],
      },
    ],
    newShapes: true,
    flats: [
      {
        id: 1,
        name: "Студия",
        type: 0,
        price: 4500000,
        layouts: ["image21.png", "image22.png"],
        house: 2,
        space: 21.4,
        amount: 2,
      },
    ],
  },
  {
    id: 6,
    name: "Плюс один",
    adress: "Ижевск, ул. Великая",
    type: "ЖК",
    location: [55.826479, 37.487208],
    district: "Стоический",
    price: 3500000,
    space: 54,
    openDate: "2025-12-12T15:00:00.000+05:00",
    image: "image19.png",
    images: ["image19.png", "image19.png", "image19.png"],
    buildings: [
      {
        id: 1,
        number: "3",
        datePic: "2025-12-12T15:00:00.000+05:00",
        images: ["image13.png", "image13.png", "image13.png"],
      },
      {
        id: 2,
        number: "2",
        datePic: "2025-12-12T15:00:00.000+05:00",
        images: ["image13.png", "image13.png", "image13.png"],
      },
    ],
    newShapes: true,
    flats: [
      {
        id: 4,
        name: "2-комн.",
        type: 2,
        price: 3000000,
        layouts: ["image23.png", "image22.png"],
        house: 2,
        space: 21.4,
        amount: 1,
      },
    ],
  },
];

export const citys = ["Москва", "Челябинск", "Саратов", "Екатеринбург"];

export const genplan = {
  // projectimg: projectImage,
  housings: [
    {
      number: 3.2,
      ready: 0.65,
      // img: sectionImage,
      flatsAmount: 97,
      date: "2022-04-11T15:00:00.000+05:00",
      styles: {
        width: "202px",
        height: "32%",
        top: "51%",
        left: "77px",
        clipPath:
          "polygon(14.85% 9.4%, 40.1% 22.3%, 68.3% 1.8%, 84.65% 9.8%, 79.2% 74.1%, 38.6% 99.1%, 2.5% 79%, 1% 20.55%)",
      },
      flats: [
        {
          name: "Студия",
          price: 3500000,
        },
        {
          name: "1-комн.",
          price: 3500000,
        },
        {
          name: "2-комн.",
          price: 4500000,
        },
        {
          name: "3-комн.",
          price: 5500000,
        },
        {
          name: "4-комн.",
          price: 6500000,
        },
      ],
      sections: [
        {
          number: "1",
          date: "2022-04-11T15:00:00.000+05:00",
          flatsAmount: 46,
          styles: {
            width: "419px",
            height: "70%",
            top: "29%",
            left: "27px",
            clipPath:
              "polygon(1.45% 15.7%, 1.45% 9%, 26.75% -0.4%, 78.75% 17.35%, 76.35% 89.6%, 53.7% 99.8%, 3.35% 73.65%, 1.45% 20.8%)",
          },
          levels: [
            {
              level: 3,
              section: "1",
              number: 3,
              oneRoomAmount: 8,
              twoRoomAmount: 4,
              treeRoomAmount: 2,
              styles: {
                width: "361px",
                height: "14%",
                top: "84%",
                left: "-237px",
                clipPath:
                  "polygon(96.95% 83.65%, 64.55% 69.4%, 42.65% 63.25%, -0.3% 78.55%, 0.3% 36.75%, 42.95% 17.35%, 96.95% 44.9%)",
              },
              flats: [
                {
                  rooms: 1,
                  styles: {
                    width: "28%",
                    height: "41%",
                    top: "55%",
                    left: "22%",
                    clipPath:
                      "polygon(59.9% 100.5%, 59.05% 81.75%, 0.45% 82.2%, 1.7% 1.45%, 100% 0.95%, 98.7% 100.5%)",
                  },
                },
              ],
            },
            {
              level: 4,
              section: "1",
              number: 4,
              oneRoomAmount: 8,
              twoRoomAmount: 4,
              treeRoomAmount: 2,
              styles: {
                width: "361px",
                height: "14%",
                top: "72%",
                left: "-237px",
                clipPath:
                  "polygon(96.95% 92.85%, 70.35% 75.5%, 42.65% 58.15%, 0% 80.6%, 0% 38.8%, 42.4% 10.2%, 96.95% 51%)",
              },
              flats: [
                {
                  rooms: 1,
                  styles: {
                    width: "28%",
                    height: "41%",
                    top: "55%",
                    left: "22%",
                    clipPath:
                      "polygon(59.9% 100.5%, 59.05% 81.75%, 0.45% 82.2%, 1.7% 1.45%, 100% 0.95%, 98.7% 100.5%)",
                  },
                },
              ],
            },
            {
              level: 6,
              section: "1",
              number: 6,
              oneRoomAmount: 8,
              twoRoomAmount: 4,
              treeRoomAmount: 2,
              styles: {
                width: "361px",
                height: "14%",
                top: "65%",
                left: "-237px",
                clipPath:
                  "polygon(96.95% 78.55%, 96.95% 105.1%, 73.95% 85.7%, 42.65% 61.2%, -0.3% 90.8%, 0% 47.95%, 43.2% 17.35%, 96.95% 62.25%)",
              },
              flats: [
                {
                  rooms: 1,
                  styles: {
                    width: "28%",
                    height: "41%",
                    top: "55%",
                    left: "22%",
                    clipPath:
                      "polygon(59.9% 100.5%, 59.05% 81.75%, 0.45% 82.2%, 1.7% 1.45%, 100% 0.95%, 98.7% 100.5%)",
                  },
                },
              ],
            },
          ],
          flats: [
            {
              name: "Студия",
              price: 3500000,
            },
            {
              name: "1-комн.",
              price: 3500000,
            },
            {
              name: "2-комн.",
              price: 4500000,
            },
            {
              name: "3-комн.",
              price: 5500000,
            },
            {
              name: "4-комн.",
              price: 6500000,
            },
          ],
        },
        {
          number: "2",
          date: "2022-04-11T15:00:00.000+05:00",
          flatsAmount: 46,
          styles: {
            width: "447px",
            height: "55%",
            top: "45%",
            left: "-420px",
            clipPath:
              "polygon(2.25% 17.15%, 10.25% 13%, 36.15% 2.1%, 79.25% 30.4%, 83.25% 99.75%, 19.4% 100.5%, 12.05% 100.25%, 6.9% 58.45%, 4.9% 41.8%)",
          },
          levels: [
            {
              level: 3,
              section: "2",
              number: 3,
              oneRoomAmount: 8,
              twoRoomAmount: 4,
              treeRoomAmount: 2,
              styles: {
                width: "361px",
                height: "14%",
                top: "84%",
                left: "-237px",
                clipPath:
                  "polygon(96.95% 83.65%, 64.55% 69.4%, 42.65% 63.25%, -0.3% 78.55%, 0.3% 36.75%, 42.95% 17.35%, 96.95% 44.9%)",
              },
              flats: [
                {
                  rooms: 1,
                  styles: {
                    width: "28%",
                    height: "41%",
                    top: "55%",
                    left: "22%",
                    clipPath:
                      "polygon(59.9% 100.5%, 59.05% 81.75%, 0.45% 82.2%, 1.7% 1.45%, 100% 0.95%, 98.7% 100.5%)",
                  },
                },
              ],
            },
            {
              level: 4,
              section: "2",
              number: 4,
              oneRoomAmount: 8,
              twoRoomAmount: 4,
              treeRoomAmount: 2,
              styles: {
                width: "361px",
                height: "14%",
                top: "72%",
                left: "-237px",
                clipPath:
                  "polygon(96.95% 92.85%, 70.35% 75.5%, 42.65% 58.15%, 0% 80.6%, 0% 38.8%, 42.4% 10.2%, 96.95% 51%)",
              },
              flats: [
                {
                  rooms: 1,
                  styles: {
                    width: "28%",
                    height: "41%",
                    top: "55%",
                    left: "22%",
                    clipPath:
                      "polygon(59.9% 100.5%, 59.05% 81.75%, 0.45% 82.2%, 1.7% 1.45%, 100% 0.95%, 98.7% 100.5%)",
                  },
                },
              ],
            },
            {
              level: 6,
              section: "2",
              number: 6,
              oneRoomAmount: 8,
              twoRoomAmount: 4,
              treeRoomAmount: 2,
              styles: {
                width: "361px",
                height: "14%",
                top: "65%",
                left: "-237px",
                clipPath:
                  "polygon(96.95% 78.55%, 96.95% 105.1%, 73.95% 85.7%, 42.65% 61.2%, -0.3% 90.8%, 0% 47.95%, 43.2% 17.35%, 96.95% 62.25%)",
              },
              flats: [
                {
                  rooms: 1,
                  styles: {
                    width: "28%",
                    height: "41%",
                    top: "55%",
                    left: "22%",
                    clipPath:
                      "polygon(59.9% 100.5%, 59.05% 81.75%, 0.45% 82.2%, 1.7% 1.45%, 100% 0.95%, 98.7% 100.5%)",
                  },
                },
              ],
            },
          ],
          flats: [
            {
              name: "Студия",
              price: 3500000,
            },
            {
              name: "1-комн.",
              price: 3500000,
            },
            {
              name: "2-комн.",
              price: 4500000,
            },
            {
              name: "3-комн.",
              price: 5500000,
            },
            {
              name: "4-комн.",
              price: 6500000,
            },
          ],
        },
      ],
    },
    {
      number: 2.1,
      ready: 0.45,
      // img: sectionImage,
      flatsAmount: 97,
      date: "2022-04-11T15:00:00.000+05:00",
      styles: {
        width: "115px",
        height: "17%",
        top: "14%",
        left: "274px",
        clipPath:
          "polygon(25.85% 1.7%, 35.35% 6.7%, 46.55% 4.2%, 64.65% 12.6%, 58.6% 8.4%, 68.1% 17.65%, 60.35% 84.05%, 49.15% 94.1%, 2.6% 79%, 13.8% 9.25%)",
      },
      flats: [
        {
          name: "Студия",
          price: 3500000,
        },
        {
          name: "1-комн.",
          price: 3500000,
        },
        {
          name: "2-комн.",
          price: 4500000,
        },
        {
          name: "3-комн.",
          price: 5500000,
        },
        {
          name: "4-комн.",
          price: 6500000,
        },
      ],
      sections: [
        {
          number: "1",
          date: "2022-04-11T15:00:00.000+05:00",
          flatsAmount: 46,
          styles: {
            width: "28%",
            height: "54%",
            top: "46%",
            left: "38%",
            clipPath:
              "polygon(1.25% 15.6%, 1.5% 10.3%, 26.65% -0.55%, 79.75% 22.2%, 77.8% 99.75%, 13.35% 99.75%, 2.2% 93.65%, 1.25% 20.65%)",
          },
          levels: [
            {
              level: 4,
              oneRoomAmount: 8,
              twoRoomAmount: 4,
              treeRoomAmount: 2,
            },
          ],
          flats: [
            {
              name: "Студия",
              price: 3500000,
            },
            {
              name: "1-комн.",
              price: 3500000,
            },
            {
              name: "2-комн.",
              price: 4500000,
            },
            {
              name: "3-комн.",
              price: 5500000,
            },
            {
              name: "4-комн.",
              price: 6500000,
            },
          ],
        },
      ],
    },
    {
      number: 1.2,
      ready: 0.85,
      // img: sectionImage,
      flatsAmount: 97,
      date: "2022-04-11T15:00:00.000+05:00",
      styles: {
        width: "115px",
        height: "26%",
        top: "24%",
        left: "172px",
        clipPath:
          "polygon(17.25% 3.85%, 28.45% 0%, 39.65% 2.75%, 46.55% 4.4%, 56.9% 6.6%, 71.55% 11%, 58.6% 80.75%, 40.5% 90.1%, 31.9% 100%, 0% 90.65%, 8.6% 8.25%)",
      },
      flats: [
        {
          name: "Студия",
          price: 3500000,
        },
        {
          name: "1-комн.",
          price: 3500000,
        },
        {
          name: "2-комн.",
          price: 4500000,
        },
        {
          name: "3-комн.",
          price: 5500000,
        },
        {
          name: "4-комн.",
          price: 6500000,
        },
      ],
      sections: [
        {
          number: "1",
          date: "2022-04-11T15:00:00.000+05:00",
          flatsAmount: 46,
          styles: {
            width: "28%",
            height: "54%",
            top: "46%",
            left: "38%",
            clipPath:
              "polygon(1.25% 15.6%, 1.5% 10.3%, 26.65% -0.55%, 79.75% 22.2%, 77.8% 99.75%, 13.35% 99.75%, 2.2% 93.65%, 1.25% 20.65%)",
          },
          levels: [
            {
              level: 4,
              oneRoomAmount: 8,
              twoRoomAmount: 4,
              treeRoomAmount: 2,
            },
          ],
          flats: [
            {
              name: "Студия",
              price: 3500000,
            },
            {
              name: "1-комн.",
              price: 3500000,
            },
            {
              name: "2-комн.",
              price: 4500000,
            },
            {
              name: "3-комн.",
              price: 5500000,
            },
            {
              name: "4-комн.",
              price: 6500000,
            },
          ],
        },
      ],
    },
  ],
};

export const favorites = [
  {
    id: 1,
    name: "Студия",
    flatNumber: 12,
    project: "Васнецово",
    projectId: 4,
    porjectType: "ЖК",
    rooms: 1,
    favored: true,
    finishingIn: false,
    level: 1,
    entrance: 5,
    street: "10 лет Октября",
    district: "Пчкаловский",
    discount: "50%",
    newShapes: true,
    type: 0,
    price: 4500000,
    finishingPrice: 477000,
    layouts: ["image21.png", "image22.png"],
    house: "2",
    space: 21.4,
    kitchenSpace: 5.7,
    degree: 120,
    amount: 2,
    openDate: "2021-10-03T15:00:00.000+05:00",
  },
  {
    id: 2,
    name: "1-комн.",
    flatNumber: 12,
    project: "Васнецово",
    projectId: 4,
    porjectType: "ЖК",
    rooms: 1,
    favored: true,
    finishingIn: true,
    level: 1,
    entrance: 5,
    street: "10 лет Октября",
    district: "Пчкаловский",
    discount: "50%",
    type: 1,
    price: 4000000,
    finishingPrice: 477000,
    layouts: ["image22.png", "image22.png"],
    house: "2",
    space: 16.4,
    kitchenSpace: 5.7,
    degree: 140,
    amount: 3,
    openDate: "2023-10-03T15:00:00.000+05:00",
    options: [
      { title: "Кладовку", image: "image31.jpg" },
      { title: "Парковку", image: "image30.jpg" },
    ],
  },
  {
    id: 4,
    name: "2-комн.",
    flatNumber: 12,
    project: "Васнецово",
    projectId: 4,
    porjectType: "ЖК",
    rooms: 1,
    favored: true,
    finishingIn: true,
    level: 1,
    entrance: 5,
    street: "10 лет Октября",
    district: "Пчкаловский",
    newShapes: true,
    type: 2,
    price: 3000000,
    finishingPrice: 477000,
    layouts: ["image23.png", "image22.png"],
    house: "2",
    space: 21.4,
    kitchenSpace: 5.7,
    degree: 0,
    amount: 1,
    openDate: "2021-10-03T15:00:00.000+05:00",
    options: [
      { title: "Кладовку", image: "image31.jpg" },
      { title: "Парковку", image: "image30.jpg" },
    ],
  },
  {
    id: 5,
    name: "3-комн.",
    flatNumber: 12,
    project: "Васнецово",
    projectId: 4,
    porjectType: "ЖК",
    rooms: 1,
    favored: true,
    finishingIn: true,
    level: 1,
    entrance: 5,
    street: "10 лет Октября",
    district: "Пчкаловский",
    type: 3,
    price: 3500000,
    finishingPrice: 477000,
    layouts: ["image23.png", "image22.png"],
    house: "2",
    space: 25.4,
    kitchenSpace: 5.7,
    degree: 70,
    amount: 12,
    openDate: "2021-10-03T15:00:00.000+05:00",
    options: [
      { title: "Кладовку", image: "image31.jpg" },
      { title: "Парковку", image: "image30.jpg" },
    ],
  },
  {
    id: 6,
    name: "4-комн.",
    flatNumber: 12,
    project: "Васнецово",
    projectId: 4,
    porjectType: "ЖК",
    rooms: 1,
    favored: true,
    finishingIn: true,
    level: 1,
    entrance: 5,
    street: "10 лет Октября",
    district: "Пчкаловский",
    discount: "50%",
    newShapes: true,
    type: 4,
    price: 3500000,
    finishingPrice: 477000,
    layouts: ["image23.png", "image22.png"],
    house: "2",
    space: 36.4,
    kitchenSpace: 5.7,
    degree: 40,
    amount: 12,
    openDate: "2021-10-03T15:00:00.000+05:00",
    options: [
      { title: "Кладовку", image: "image31.jpg" },
      { title: "Парковку", image: "image30.jpg" },
    ],
  },
  {
    id: 7,
    name: "4-комн.",
    flatNumber: 12,
    project: "Васнецово",
    projectId: 4,
    porjectType: "ЖК",
    rooms: 1,
    favored: true,
    finishingIn: true,
    level: 1,
    entrance: 5,
    street: "10 лет Октября",
    district: "Пчкаловский",
    discount: "50%",
    newShapes: true,
    type: 4,
    price: 3500000,
    finishingPrice: 477000,
    layouts: ["image23.png", "image22.png"],
    house: "2",
    space: 36.4,
    kitchenSpace: 5.7,
    degree: 40,
    amount: 12,
    openDate: "2021-10-03T15:00:00.000+05:00",
    options: [
      { title: "Кладовку", image: "image31.jpg" },
      { title: "Парковку", image: "image30.jpg" },
    ],
  },
  {
    id: 1,
    name: "Студия",
    flatNumber: 12,
    project: "Васнецово",
    projectId: 4,
    porjectType: "ЖК",
    rooms: 1,
    favored: true,
    finishingIn: true,
    level: 1,
    entrance: 5,
    street: "10 лет Октября",
    district: "Пчкаловский",
    discount: "50%",
    newShapes: true,
    type: 0,
    price: 4500000,
    finishingPrice: 477000,
    layouts: ["image21.png", "image22.png"],
    house: "2",
    space: 21.4,
    kitchenSpace: 5.7,
    degree: 120,
    amount: 2,
    openDate: "2021-10-03T15:00:00.000+05:00",
  },
  {
    id: 2,
    name: "1-комн.",
    flatNumber: 12,
    project: "Васнецово",
    projectId: 4,
    porjectType: "ЖК",
    rooms: 1,
    favored: true,
    finishingIn: true,
    level: 1,
    entrance: 5,
    street: "10 лет Октября",
    district: "Пчкаловский",
    discount: "50%",
    newShapes: true,
    type: 1,
    price: 4000000,
    finishingPrice: 477000,
    layouts: ["image22.png", "image22.png"],
    house: "2",
    space: 16.4,
    kitchenSpace: 5.7,
    degree: 140,
    amount: 3,
    openDate: "2023-10-03T15:00:00.000+05:00",
    options: [
      { title: "Кладовку", image: "image31.jpg" },
      { title: "Парковку", image: "image30.jpg" },
    ],
  },
  {
    id: 4,
    name: "2-комн.",
    flatNumber: 12,
    project: "Васнецово",
    projectId: 4,
    porjectType: "ЖК",
    rooms: 1,
    favored: true,
    finishingIn: true,
    level: 1,
    entrance: 5,
    street: "10 лет Октября",
    district: "Пчкаловский",
    discount: "50%",
    newShapes: true,
    type: 2,
    price: 3000000,
    finishingPrice: 477000,
    layouts: ["image23.png", "image22.png"],
    house: "2",
    space: 21.4,
    kitchenSpace: 5.7,
    degree: 0,
    amount: 1,
    openDate: "2021-10-03T15:00:00.000+05:00",
    options: [
      { title: "Кладовку", image: "image31.jpg" },
      { title: "Парковку", image: "image30.jpg" },
    ],
  },
  {
    id: 5,
    name: "3-комн.",
    flatNumber: 12,
    project: "Васнецово",
    projectId: 4,
    porjectType: "ЖК",
    rooms: 1,
    favored: true,
    finishingIn: true,
    level: 1,
    entrance: 5,
    street: "10 лет Октября",
    district: "Пчкаловский",
    discount: "50%",
    newShapes: true,
    type: 3,
    price: 3500000,
    finishingPrice: 477000,
    layouts: ["image23.png", "image22.png"],
    house: "2",
    space: 25.4,
    kitchenSpace: 5.7,
    degree: 70,
    amount: 12,
    openDate: "2021-10-03T15:00:00.000+05:00",
    options: [
      { title: "Кладовку", image: "image31.jpg" },
      { title: "Парковку", image: "image30.jpg" },
    ],
  },
  {
    id: 6,
    name: "4-комн.",
    flatNumber: 12,
    project: "Васнецово",
    projectId: 4,
    porjectType: "ЖК",
    rooms: 1,
    favored: true,
    finishingIn: true,
    level: 1,
    entrance: 5,
    street: "10 лет Октября",
    district: "Пчкаловский",
    discount: "50%",
    newShapes: true,
    type: 4,
    price: 3500000,
    finishingPrice: 477000,
    layouts: ["image23.png", "image22.png"],
    house: "2",
    space: 36.4,
    kitchenSpace: 5.7,
    degree: 40,
    amount: 12,
    openDate: "2021-10-03T15:00:00.000+05:00",
    options: [
      { title: "Кладовку", image: "image31.jpg" },
      { title: "Парковку", image: "image30.jpg" },
    ],
  },
  {
    id: 7,
    name: "4-комн.",
    flatNumber: 12,
    project: "Васнецово",
    projectId: 4,
    porjectType: "ЖК",
    rooms: 1,
    favored: true,
    finishingIn: true,
    level: 1,
    entrance: 5,
    street: "10 лет Октября",
    district: "Пчкаловский",
    discount: "50%",
    newShapes: true,
    type: 4,
    price: 3500000,
    finishingPrice: 477000,
    layouts: ["image23.png", "image22.png"],
    house: "2",
    space: 36.4,
    kitchenSpace: 5.7,
    degree: 40,
    amount: 12,
    openDate: "2021-10-03T15:00:00.000+05:00",
    options: [
      { title: "Кладовку", image: "image31.jpg" },
      { title: "Парковку", image: "image30.jpg" },
    ],
  },
];
