export const newsCards = [
  {
    id: 1,
    title:
      "Лес начинается с тебя новые экологичные проекты для комфортной жизни",
    desc: "Темп глобализации постоянно растет, и большая часть украинских девелоперов теперь ничем не отличается от застройщиков из Китая, США",
    date: "9 октября 2021",
  },
  {
    id: 2,
    title: "17 лет только начало",
    desc: "Темп глобализации постоянно растет, и большая часть украинских девелоперов теперь ничем не отличается от застройщиков из Китая, США",
    date: "9 октября 2021",
  },
  {
    id: 3,
    title: "Лес начинается с тебя новые экологичные проекты",
    desc: "Темп глобализации постоянно растет, и большая часть украинских девелоперов теперь ничем не отличается от застройщиков из Китая, США",
    date: "9 октября 2021",
  },
];

export const houseCards = [
  {
    id: 1,
    name: "Forest",
    adress: "Ижевск, ул. Союзная",
    type: "ЖК",
    district: "Ульяновский",
    location: [55.684758, 37.738521],
    price: 3500000,
    space: 70,
    openDate: "2017-05-15T08:30:00.000+05:00",
    image: "image13.png",
    images: ["image13.png", "image13.png", "image13.png"],
    buildings: [
      {
        id: 1,
        number: "3",
        datePic: "2017-05-15T08:30:00.000+05:00",
        images: ["image24.png", "image25.png", "image26.png"],
      },
      {
        id: 2,
        number: "2",
        datePic: "2017-05-15T08:30:00.000+05:00",
        images: ["image25.png", "image24.png", "image26.png"],
      },
    ],
    discount: "10%",
    newShapes: true,
    flats: [
      {
        id: 2,
        name: "1-комн.",
        type: 1,
        price: 4000000,
        layouts: ["image22.png", "image22.png"],
        house: 2,
        space: 16.4,
        amount: 3,
      },
      {
        id: 4,
        name: "2-комн.",
        type: 2,
        price: 3000000,
        layouts: ["image23.png", "image22.png"],
        house: 2,
        space: 21.4,
        amount: 1,
      },
      {
        id: 5,
        name: "3-комн.",
        type: 3,
        price: 3500000,
        layouts: ["image23.png", "image22.png"],
        house: 2,
        space: 25.4,
        amount: 12,
      },
    ],
  },
  {
    id: 2,
    name: "Forest",
    adress: "Ижевск, ул. Союзная",
    type: "ЖК",
    location: [55.833436, 37.715175],
    district: "Ульяновский",
    price: 4500000,
    space: 24,
    openDate: "2028-08-10T12:00:00.000+05:00",
    image: "image16.png",
    images: ["image16.png", "image16.png", "image16.png"],
    buildings: [
      {
        id: 1,
        number: "3",
        datePic: "2028-08-10T12:00:00.000+05:00",
        images: ["image24.png", "image25.png", "image26.png"],
      },
      {
        id: 2,
        number: "2",
        datePic: "2028-08-10T12:00:00.000+05:00",
        images: ["image25.png", "image24.png", "image26.png"],
      },
    ],
    discount: "50%",
    newShapes: true,
    flats: [
      {
        id: 2,
        name: "1-комн.",
        type: 1,
        price: 4000000,
        layouts: ["image22.png", "image22.png"],
        house: 2,
        space: 16.4,
        amount: 3,
      },
    ],
  },
  {
    id: 3,
    name: "Плюс один",
    adress: "Ижевск, ул. Союзная",
    type: "ЖК",
    location: [55.687086, 37.529789],
    district: "Ульяновский",
    price: 6500000,
    space: 224,
    openDate: "2021-02-20T15:00:00.000+05:00",
    image: "image17.png",
    images: ["image17.png", "image17.png", "image17.png"],
    buildings: [
      {
        id: 1,
        number: "3",
        datePic: "2021-02-20T15:00:00.000+05:00",
        images: ["image24.png", "image25.png", "image26.png"],
      },
      {
        id: 2,
        number: "2",
        datePic: "2021-02-20T15:00:00.000+05:00",
        images: ["image25.png", "image24.png", "image26.png"],
      },
    ],
    newShapes: true,
    flats: [
      {
        id: 1,
        name: "Студия",
        type: 0,
        price: 4500000,
        layouts: ["image21.png", "image22.png"],
        house: 2,
        space: 21.4,
        amount: 2,
      },
      {
        id: 2,
        name: "1-комн.",
        type: 1,
        price: 4000000,
        layouts: ["image22.png", "image22.png"],
        house: 2,
        space: 16.4,
        amount: 3,
      },
    ],
  },
  {
    id: 4,
    name: "Васнецово",
    adress: "Ижевск, ул. Танкограда",
    type: "ЖК",
    about: {
      text: [`Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`, `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`],
      images: ["image27.jpg", "image26.jpg", "image27.jpg"]
    },
    location: [55.782392, 37.611724],
    nearerObjects: [
      {
        id: 1,
        location: [55.782602, 37.614034],
        type: "culture",
        title: "Театр",
        infoLeft: "1060 мест",
        infoRight: "с 1960г"
      },
      {
        id: 2,
        location: [55.782192, 37.611524],
        type: "medecine",
        title: "поликлиника",
        infoLeft: "Лотос",
      },
      {
        id: 3,
        location: [55.782182, 37.611834],
        type: "education",
        title: "Школа",
        infoLeft: "1060 мест",
        infoRight: "Сдан"
      },
      {
        id: 4,
        location: [55.782082, 37.611934],
        type: "shop",
        title: "Магазины",
        infoLeft: "Reserved, Cropp, Zara",
      },
      {
        id: 5,
        location: [55.782882, 37.610834],
        type: "food",
        title: "Семейный ресторан",
        infoLeft: "Своя компания",
        infoRight: "₽₽"
      },
      {
        id: 6,
        location: [55.782582, 37.612834],
        type: "sport",
        title: "Спортзал",
      },
      {
        id: 7,
        location: [55.782452, 37.612634],
        type: "transport",
        title: "Метро",
        infoLeft: "Остановка 'Достоевская'",
      },
      {
        id: 8,
        location: [55.782300, 37.611934],
        type: "kindergarden",
        title: "Детский сад",
        infoLeft: "400 мест",
        infoRight: "Сдан"
      },
    ],
    district: "Пчкаловский",
    price: 3000000,
    space: 124,
    openDate: "2021-10-03T15:00:00.000+05:00",
    image: "image27.jpg",
    images: ["image27.jpg", "image26.jpg", "image27.jpg"],
    buildings: [
      {
        id: 1,
        number: "3",
        datePic: "2021-10-03T15:00:00.000+05:00",
        images: ["image24.png", "image25.png", "image26.png"],
      },
      {
        id: 2,
        number: "2",
        datePic: "2021-12-03T15:00:00.000+05:00",
        images: ["image25.png", "image24.png", "image26.png"],
      },
      {
        id: 3,
        number: "4",
        datePic: "2021-12-03T15:00:00.000+05:00",
        images: ["image26.png", "image24.png", "image25.png"],
      },
    ],
    discount: "10%",
    newShapes: true,
    flats: [
      {
        id: 1,
        name: "Студия",
        type: 0,
        price: 4500000,
        layouts: ["image21.png", "image22.png"],
        house: 2,
        space: 21.4,
        amount: 2,
        about: {
          title: "Отделка",
          text: [`Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`, `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`],
          images: ["image28.jpg", "image29.jpg", "image28.jpg"]
        },
       options: [{title: "Кладовку", image: "image31.jpg"}, {title: "Парковку", image: "image30.jpg"}]
      },
      {
        id: 2,
        name: "1-комн.",
        type: 1,
        price: 4000000,
        layouts: ["image22.png", "image22.png"],
        house: 2,
        space: 16.4,
        amount: 3,
        about: {
          title: "Отделка",
          text: [`Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`, `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`],
          images: ["image29.jpg", "image28.jpg", "image29.jpg"]
        },
        options: [{title: "Кладовку", image: "image31.jpg"}, {title: "Парковку", image: "image30.jpg"}]
      },
      {
        id: 4,
        name: "2-комн.",
        type: 2,
        price: 3000000,
        layouts: ["image23.png", "image22.png"],
        house: 2,
        space: 21.4,
        amount: 1,
        about: {
          title: "Отделка",
          text: [`Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`, `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`],
          images: ["image28.jpg", "image29.jpg", "image28.jpg"]
        },
        options: [{title: "Кладовку", image: "image31.jpg"}, {title: "Парковку", image: "image30.jpg"}]
      },
      {
        id: 5,
        name: "3-комн.",
        type: 3,
        price: 3500000,
        layouts: ["image23.png", "image22.png"],
        house: 2,
        space: 25.4,
        amount: 12,
        about: {
          title: "Отделка",
          text: [`Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`, `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`],
          images: ["image29.jpg", "image28.jpg", "image29.jpg"]
        },
        options: [{title: "Кладовку", image: "image31.jpg"}, {title: "Парковку", image: "image30.jpg"}]
      },
      {
        id: 6,
        name: "4-комн.",
        type: 4,
        price: 3500000,
        layouts: ["image23.png", "image22.png"],
        house: 2,
        space: 36.4,
        about: {
          title: "Отделка",
          text: [`Расположение комплекса вблизи хвойного леса настраивает на гармонию с природой. 5 домов с огороженной территорией предполагают приватную атмосферу, где новоселам будет комфортно жить вне городской суеты.`, `Первый дом комплекса будет 17-этажным и иметь два подъезда. Во внешнем облике используется кирпич различных оттенков, образующих градиентные переходы на фасаде. В качестве ярких акцентов желтым выделены лоджии с панорамным остеклением.`],
          images: ["image28.jpg", "image29.jpg", "image28.jpg"]
        },
        options: [{title: "Кладовку", image: "image31.jpg"}, {title: "Парковку", image: "image30.jpg"}]
      },
    ],
  },
  {
    id: 5,
    name: "ARTNOVA",
    adress: "Ижевск, ул. Великая",
    type: "ЖК",
    location: [55.642063, 37.656123],
    district: "Стоический",
    price: 6500000,
    space: 14,
    openDate: "2022-04-11T15:00:00.000+05:00",
    image: "image18.png",
    images: ["image18.png", "image18.png", "image18.png"],
    buildings: [
      {
        id: 1,
        number: "3",
        datePic: "2022-04-11T15:00:00.000+05:00",
        images: ["image13.png", "image13.png", "image13.png"],
      },
      {
        id: 2,
        number: "2",
        datePic: "2022-04-11T15:00:00.000+05:00",
        images: ["image13.png", "image13.png", "image13.png"],
      },
    ],
    newShapes: true,
    flats: [
      {
        id: 1,
        name: "Студия",
        type: 0,
        price: 4500000,
        layouts: ["image21.png", "image22.png"],
        house: 2,
        space: 21.4,
        amount: 2,
      },
    ],
  },
  {
    id: 6,
    name: "Плюс один",
    adress: "Ижевск, ул. Великая",
    type: "ЖК",
    location: [55.826479, 37.487208],
    district: "Стоический",
    price: 3500000,
    space: 54,
    openDate: "2025-12-12T15:00:00.000+05:00",
    image: "image19.png",
    images: ["image19.png", "image19.png", "image19.png"],
    buildings: [
      {
        id: 1,
        number: "3",
        datePic: "2025-12-12T15:00:00.000+05:00",
        images: ["image13.png", "image13.png", "image13.png"],
      },
      {
        id: 2,
        number: "2",
        datePic: "2025-12-12T15:00:00.000+05:00",
        images: ["image13.png", "image13.png", "image13.png"],
      },
    ],
    newShapes: true,
    flats: [
      {
        id: 4,
        name: "2-комн.",
        type: 2,
        price: 3000000,
        layouts: ["image23.png", "image22.png"],
        house: 2,
        space: 21.4,
        amount: 1,
      },
    ],
  },
];

export const citys = ["Москва", "Челябинск", "Саратов", "Екатеринбург"];
